### ISSUE TITLE
Broken Interpolation in CoffeeScript strings

### ISSUE THREAD

**Issue by jkeks** [pugjs/pug#1100]
Broken Interpolation in CoffeeScript strings

```
$("#clock").html('<date>'+years+'.#{monthss}</date>')
```

_years_ will show
but 
_monthss_ - will not

use with Prepros

**Comment by joepie91** [comment]
@ForbesLindesay Surely it should be possible to specify an interpolation-free text block? That seems like it'd solve the problem, and not be an unreasonable burden syntax-wise.

**Comment by TimothyGu** [comment]
@joepie91 this has been fixed in Jade 2.0.

```jade
script
  :coffee-script
    hey = 2
    console.log "#{hey}"
```

will render to:

```html
<script>(function() {
  var hey;

  hey = 2;

  console.log("" + hey);

}).call(this);
</script>
```

There is no support for a specific kind of interpolation-free block, but internally there is a state variable `interpolationAllowed` that could be easily used when one wants to write a plugin or something. Currently the boolean is turned off when a block code, block comment, or filtering is encountered.

**Comment by joepie91** [comment]
Aha, I see. I didn't find a reference to that on the 'plain text' page of the documentation... did I overlook something, or is it just not there?

**Comment by TimothyGu** [comment]
@joepie91 Yes! `npm i --save jstransformer-verbatim` and `:verbatim`.

**Comment by joepie91** [comment]
Thanks! That seems like it'd make a useful addition to the documentation :)
