### ISSUE TITLE
Conditional Comments

### ISSUE THREAD

**Issue by gisu** [pugjs/pug#1345]
Any Conditional Comments didn't work with JADE 1.0. 

```
//if lt IE 8
  link(rel='stylesheet', href='style-ie8.css')
```

Gives

```
<!-- if lt IE 8link(rel='stylesheet', href='components/css/style-ie8.css')
-->
```

Is this a bug, is this functionality dropped its a new secrete option that i have to activate?

**Comment by GeorgeWL** [comment]
@louh  @ForbesLindesay 

You're missing out edge cases over here.

Nodemailer and other Mail-sender packages can use Pug Templates to generate the HTML used for E-mails and since no major email clients follow even HTML 4 spec, never mind HTML 5, conditionals are actually a requirement to hack your way around the god damn stupidity that many email clients have.
