### ISSUE TITLE
Multiple basedirs

### ISSUE THREAD

**Issue by domachine** [pugjs/pug#1721]
It would be nice if one could specify multiple `basedir`s e.g. as array. In the style of the unix `$PATH` variable or node's `require` resolving mechanism. Couldn't find anything to realize that. Would that match the design of jade or am I thinking in the wrong scope?

Regards, domachine

**Comment by rootical** [comment]
Having the same problem :( As for it makes a lot of sense and taking consideration a big number of issues on this topic for others as well. I want to have one module taking care of layouts building and mixins carrier. `basedir` is definitely not enough here since I would prefer using `includes` or `extends` within seperated packages as well. 
Looking forward for any workarounds community suggests, trying to set up my own.
