### ISSUE TITLE
Possible to wildcard include?

### ISSUE THREAD

**Issue by ghost** [pugjs/pug#1789]
so im wishing to add a blog to my personal site in the hackiest way possible, and i thought what if i could do `include *.markdown` is this possible?

**Comment by smaudet** [comment]
Have to disagree here...might not make sense in all use cases but it seems like a lot of people are looking for the ability to include files at compile time. I'm looking to do nearly the exactly same thing, I don't see why it shouldn't be a compile thing.

But maybe the problem is the syntax isn't invented and it would be confusing to overload include at this point to some people.

**Comment by Cactucs** [comment]
I would like it. I have folder of mixins (One mixin - one file) and I would like to import them all...

**Comment by arxpoetica** [comment]
And can't tell you the number of times I go looking for this feature. I'll list a few examples.

Scenario 1: I have a bunch of script components for Svelte.js: it doesn't matter the load order since Svelte just cares that you include the `<script>` tags somewhere on the page before compiling the Svelte, but even if it did, alphabetical include would be a pretty reliable go to. This is a common scenario for oodles of different JS frameworks.

Scenario 2: mixins broken out into different files. Would be nice to just import the whole folder, not manually keep track every time I add a new one.

Scenario 3: lists of content can sometimes inhabit a lot of space on a page; one might like to break them out if they have a ton to load (think tables or ul/ol lists), and then just include the whole folder.

Etc.

**Comment by thanatoid** [comment]
I have scenario 2 that @arxpoetica mentioned - I have a template for ajax responses that will dynamically add what ever mixin I'm looking to insert, and it'd be very convenient to just include the folder and call it done, rather than include each individual mixin every time I add one.

**Comment by ForbesLindesay** [comment]
You can just create an `index.pug` file that looks like:

```pug
include a.pug
include b.pug
include c.pug
```

then you just have to include that `index.pug` file. I think maintaining this list is a lower cost than adding a wildcard/directory include feature to pug would be at this point.
