### ISSUE TITLE
CLI option `jade --watch` broken 

### ISSUE THREAD

**Issue by flintinatux** [pugjs/pug#1795]
When using the `--watch` option in CLI mode, the first render works fine, but subsequent renders fail on file changes with an error message similar to the following.

```
$ jade -P -w client/*.jade -o public

\
  rendered public/index.html
TypeError: path must be a string
    at Object.fs.lstat (fs.js:669:11)
    at renderFile (/Users/scott/flintinatux/mithril-todos/node_modules/jade/bin/jade.js:172:6)
    at StatWatcher.<anonymous> (/Users/scott/flintinatux/mithril-todos/node_modules/jade/bin/jade.js:119:11)
    at StatWatcher.emit (events.js:98:17)
    at StatWatcher._handle.onchange (fs.js:1109:10)
```

This is a not an issue with the previous version (1.8.1), so for now I've just locked my dependency to that version.

**Comment by TimothyGu** [comment]
@flintinatux See #1803 for a rudimentary test for the watch mode. I would appreciate any reviews as I am nervous about all the spawning trickery/hackery.

**Comment by robmuh** [comment]
Just want to thank you for your quick attention to this. I've confirmed it is working as well. Will this be in a 1.8.3 release eventually? No rush, but semester starts on Jan 5th and my Web-2 students usually get thrown into Jade from the very beginning. (We start with basic `npm install -g jade` and then `-w` stuff instead of the other prepros tools and workflows to get a feel for what is happening.)

**Comment by TimothyGu** [comment]
@robmuh I am sure it will be in 1.8.3, but the release date for 1.8.3 depends entirely on the availability of @ForbesLindesay. BTW, there is a college course for Jade? I would really want to take that class.

**Comment by robmuh** [comment]
Thanks for the info. Not college, our nano-school (SkilStak Coding Arts)[http://skilstak.com) where I've been introducing kids as young as 10 to Jade after they get a general feel for HTML/CSS, etc. Jade and Stylus actually make web development easier for these guys because they have started their code lives on Python.

**Comment by TimothyGu** [comment]
@robmuh Ah ok. I'm just a little bit too old. :)
