### ISSUE TITLE
Customizing Jade

### ISSUE THREAD

**Issue by TimothyGu** [pugjs/pug#2133]
Now that we have modularized Jade, how does one customize these modules in Jade?

## Lexer, Parser, and Code Generator
The old `Lexer`, `Parser`, and `Compiler` options and exported objects are gone. How do users customize them then? Should we export them again?

## Plugins
There is no plugin architecture in Jade; if a user wants to modify the AST before sending it to code-gen he/she has to fork the entire Jade source.

I propose we add a plugin system, in which plugins are first defined through an exported object of plugins that is filled with default ones:

```js
exports.tokenPlugins = {
  stripComments: function (tokens, filename) {
    return stripComments(tokens, { filename: filename });
  }
};
exports.plugins = {
  link: function (ast) {
    return link(ast);
  },
  filters: function (ast) {
    return filters.handleFilters(ast, exports.filters);
  }
};
```

The user can then extend the plugins:

```js
var jade = require('jade');
jade.plugins.mySpecialOne = function (ast) {
  ast.nodes = [{type: 'Text', val: 'You are my special one!', line: 1}];
  return ast;
};
```

And finally `options.tokenPlugins` and `options.plugins` are available for user to choose which plugins to enable, and in which order:

```js
// Defaults:
// plugins: ['link', 'filters']
// tokenPlugins: ['stripComments']
jade.compile('', {plugins: ['mySpecialOne']});
```

## File Loader
I don't see an easy way of customizing this, especially with regards to pushing entries to the dependencies object.

**Comment by ForbesLindesay** [comment]
My preference would be to have plugins be separate npm packages, and have them be passed as objects to a `plugins` option in `jade.compile`.  I see us as having the following hooks:

- preLex (function that takes a string and returns a string)
- lex (object who's functionality should be defined by the lexer)
- postLex (function that takes an array of tokens and returns a new array of tokens)
- preParse (function that takes an array of tokens and returns a new array of tokens)
- parse (object who's functionality should be defined by the parser)
- postParse (function that takes an AST and returns an AST)
- preLoad (function that takes an AST and returns an AST)
- load (object who's functionality should be defined by the loader)
- postLoad (function that takes an AST and returns an AST)
- preLink (function that takes an AST and returns an AST)
- link (object who's functionality should be defined by the linker)
- postLink (function that takes an AST and returns an AST)
- preCodeGen (function that takes an AST and returns an AST)
- codeGen (object who's functionality should be defined by the code-gen)
- postCodeGen (function that takes an string of JavaScript and returns a string of JavaScript)


## lex

The `lex` plugins should be able to  define a function to be run at the start of the `advance` method that should take the entire lexer and return `true` (if it's consumed some of the text) or `false` otherwise.  This will easily support multiple plugins simultaneously.

## parse

The `parse` plugins should be able to  define a function to handle a given token type in any of the switch statements in the parser.  Again, this should support multiple plugins simultaneously as long as they're not trying to override/handle the same token.  In that case we'll have to decide which plugin wins, or throw an error.

## load

The `load` plugins should be able to override `resolve` and `read`.  Maybe the `jade-load` module itself should handle tracking dependencies.  Alternatively maybe the dependencies should be tracked by a plugin.  We could handle multiple plugins wanting to override `resolve` by simply passing the path to each `resolve` once after another.  Handling multiple plugins overriding `read` might be more tricky, but it could be done if we let the plugins define a prefix, or perhaps fall through when a `read` throws an error of an appropriate type.

## link

I have no idea what a linker plugin would look like, maybe this shouldn't exist?

## code-gen

Should allow the user to define a function to be called for a given AST node.

**Comment by TimothyGu** [comment]
How would the order of how the plugins be applied be selected?

**Comment by ForbesLindesay** [comment]
The user would pass the plugins as an array so we would just use the order of the array.  For most plugins it probably won't end p mattering anyway, and most users should only have a handful of plugins.

**Comment by TimothyGu** [comment]
So I'm drafting an `options.plugins` for the main jade module. This is the approach I have on mind:

## The Plugin Module

Individual plugins are just a function accepting an option object, returning an object with hook names as properties.

```js
module.exports = function (options) {
  return {
    lex: {
      advance: function (lexer) {
        // blah blah
      }
    },
    parse: {
      expressionTokens: {
        id: function (parser) {
          // codez
        }
      }
    }
  };
};
```

## The Main File

I would have used an object with the module name as the property key, but we need to preserve the order here, so I decided on the array approach.

```js
var plugins = [
  require('jade-module-name')({option1: true}),
  require('./my-own')({moreOption: ['hmm']}),
  'jade-more-module' // equivalent to require('jade-more-module')({})
];

jade.render('#id: p hey', {plugins});
```

**Comment by ForbesLindesay** [comment]
Looks good.  One small nit, lets encourage all plugins to be called `jade-plugin-<my-plugin-name>` so in your example:

```js
var plugins = [
  require('jade-plugin-module-name')({option1: true}),
  require('./my-own')({moreOption: ['hmm']}),
  'more-module' // equivalent to require('jade-plugin-more-module')()
];

jade.render('#id: p hey', {plugins});
```

We should also tag all the ones we produce as `jade-plugin` so they are discoverable on npm.

**Comment by TimothyGu** [comment]
Pug plugins have been implemented.
