### ISSUE TITLE
What is the status of the name change (jade => pug)?

### ISSUE THREAD

**Issue by callumlocke** [pugjs/pug#2285]
I know there is another issue #2184 about this, but it's locked and I can't tell if the checklist there is being updated.

Is this name change still being actively pursued? Is jade-lang.org going to be redirected at some point? Is pug-lang.com actually available for pug to use, and if not, why does the readme still link to this apparently unrelated website? Is there any timeframe for completing this name change?

**Comment by antoniobrandao** [comment]
Sorry if this is not the right place but I don't know where else to share this. I just want to express my disappointment with the choice of the new name. And logo. How can you go from a precious stones' beautiful name to a minimal dog's name? Jade always represented to me something like a precious, exquisite way of writing CSS, and now it's like a toddler's toy brand identity. It might as well have been a cute cat instead. Not very unique. Don't take me wrong, I love pugs. But you could have tried another precious stone or anything exquisite sounding. I always loved Jade, it was such a cool name. It was even nice to _say_ jade. It's like if all these years I had a great looking Ferrari, and now someone tuned it to look like a puppy car.

It would be really awesome, in the spirit of the open source, if you guys would open a poll for suggestions and then for voting, to get a great name together that has the love of the community.

**Comment by justsml** [comment]
+100000 @antoniobrandao 

This is almost as welcome a Coca-Cola's 'New Code' #fail

This is such an unforced error. 

I just hope some one has the good sense to reverse this craziness before it harms the brand recognition of THE best template language around: **JADE**

**Comment by cherstewart** [comment]
#puggate

**Comment by antoniobrandao** [comment]
Thanks @justsml. I hope they hear us.

**Comment by alubbe** [comment]
Among the contributors, we had a very long email discussion last November, when it became clear that we couldn't keep the name jade. Essentially, there were two directions: either going with something representing the beauty of the language (such as other gemstones or misspellings of "jade") or choosing something representing the modular, plugin-based future of the project that allows it to easily adopt new technologies such as react, promises, etc.

There was a lot of back and forth and I personally argued for other gemstone-related names, but almost all of those names were taken on npm, or had trademarks in the UK (like jade). So ultimately Forbes Lindsay started playing with word "plugin" and "pug" just struck a chord, as it is "short, memorable and un-trademarked". We all agreed that this project is ultimately his baby and he gets to make the call.

I hope this gives you some insight that this decision was not made lightly or hastily. Also, we all would have preferred to stick with jade, but we checked with lawyers and the potential 6-7 digit cost associated with losing the lawsuit swayed us.

**Comment by antoniobrandao** [comment]
@alubbe  Thanks I appreciate your reply. I thought project Jade was TJ Holowaychuk's baby? I do believe the decision wasn't taken hastly. I also understand you really had to move away from the name Jade. I understand a new name was really necessary. And personally, I would not be a great supporter of variations like "Jaed" because they are to weird and different to remember. I would have gone for some other memorable precious mineral or something in those lines.

When you say this project is Lindsay's baby, I understand you have in mind the plans for the future of the project - a leap into something new - a new modular kind of Jade as you say, plugin based, that can adopt technologies like React, Promises, etc.

But you see, you made a "versus" decision of: "plugin/modular architecture" VS "beauty of the language".

Think about it. Who should really take the lead from those two? Which one is more intemporal? I just say this: How many languages could choose their name in regard to their plugin/modular architecture? And how many languages can choose their name based on the beauty of their code? Take a while to think about that.

Jade, has the privilege of being able to choose a name based on it's beauty of code. It's not a common privilege! :)

This hype surrounding the upcoming architecture, is just temporary, and ephemeral. It's great, but after it is done, it will be just another feature, like the other features, features that aren't even unique to Pug. Choosing the name based on a new architecture will make the name pointless in the future when the architecture is taken for granted. Features and architectures and always changing. It's the personality of the language (syntax) that people remember.

One can't just go from an exquisite stone to a dog. All my files are ".jade" and they will be ".pug" now. It's like if they were ".dog" now. Feels so common and un-classy!

It's really awesome that the new architecture is coming. I'm sure it will make the language shine in many circles, maybe even increase adoption a lot. But, is it the only language with these feature? Does it make it unique? If yes, for how long? I'm sure others will follow. Most people, like me, just use the language because it is so perfect and beautiful to code. If it has plugins, modular, architecture, great, but Jade/Pug can't be the only kid on the block with an iphone for long.

For me and many others, what makes Jade really stand out among other templating languages, is that the syntax doens't suck, doesn't get in the way, it's actually great looking and really easy to read - compared to underscore, handlebars, EJS, it's blissful.

In the long run, all of those other templating languages may become modular and plugin based as well! It's just a commodity. But hardly any one can be so pleasing to write and read like Jade!

I think you get my point. It's a better choice to name a project after it's best, most intemporal feature. In the case of Jade, is it's class and beauty. The super DRY code. Not the architecture. Even "DRY" would make a better name.

Some questions:

1 - Isn't it possible to have a name that it not "Jade" but includes the word? Like "JadeCSS" or "Jadelang" as oficial name? Is that also not allowed?

2 - Couldn't you guys open a poll where the community can make suggestions? In the spirit of open source. Something great could come up having many minds working together!

3 - Are you guys aware the in Russian, Pug is a bad-sounding dirty word?

Please don't be annoyed by me. I love Jade since I saw it the first time. It will feel most disturbing to use .pug files instead of .jade files.

Thanks

**Comment by TimothyGu** [comment]
> I thought project Jade was TJ Holowaychuk's baby?

It [was](https://medium.com/@tjholowaychuk/farewell-node-js-4ba9e7f3e52b).

> 1 - Isn't it possible to have a name that it not "Jade" but includes the word? Like "JadeCSS" or "Jadelang" as oficial name? Is that also not allowed?

Unfortunately no, since "Jadelang" is easily understood a portmanteau of "Jade" (the trademark) and "lang"/language.

> 2 - Couldn't you guys open a poll where the community can make suggestions? In the spirit of open source. Something great could come up having many minds working together!

While I am all for the spirit of open source, the reason as I understood it was that we didn't want to make the company the target of criticism before the decision to change the name was final. @ForbesLindesay might have some additional reasons.

> 3 - Are you guys aware the in Russian, Pug is a bad-sounding dirty word?

Yes, but "pug" as pronounced in English is closer to «паг» (_pag_) than «пуг» (_poog,_ the bad word), so we didn't think it would be a great problem.

**Comment by TimothyGu** [comment]
> Is this name change still being actively pursued?

Yes.

> Is jade-lang.org going to be redirected at some point?

Probably.

> Is pug-lang.com actually available for pug to use, and if not, why does the readme still link to this apparently unrelated website? Is there any timeframe for completing this name change?

The domain stuff I have to leave to @ForbesLindesay, since he owns the domains. He seems to be pretty busy unfortunately so there is no clear time frame.

**Comment by TimothyGu** [comment]
I'm going to close this ticket but don't let that stop your comment.
