### ISSUE TITLE
Is Pug production ready?

### ISSUE THREAD

**Issue by joeyfromspace** [pugjs/pug#2323]
Is the Pug package on NPM (2.0.0-alpha6) good for use in production? The alpha6 has me wondering. I can't tell if the code itself has issues or if it's just due to the lack of website, logo, docs, etc.

**Comment by ForbesLindesay** [comment]
It's because if unintentional breaking changes from jade@1 are found we will still fix them, which may itself be a breaking chnange.  I'd say it's safe to use providing you typically install updates at least once a week and are willing to thoroughly test each update.  I've started porting my own websites across and will remove the alpha tag as soon as I'm confident we've squashed all the major bugs.
