### ISSUE TITLE
Include issue with 2.0.0-alpha6

### ISSUE THREAD

**Issue by jcwren** [pugjs/pug#2349]
(This could possibly be considered a duplicate of #2344, but the symptoms are a little different.)

Switched from jade to pug by changing the view engine, copied all the .jade files to .pug's. Whereas before this worked with jade, now the content in menu.pug (below) is being rendered as text (from Chrome's console):

```
<body>
  <div style="display: none" theme="#{theme}" menuautoopen="#{menuautoopen}" id="pmmui"></div>
  "div.hideondisconnect.no-print#jqxMenu
   input(type='hidden' value="#{pmmmatchtype}")#menu_matchtype
   ul    
     li File 
       ul
       ...
  "
```
index.pug:
```
extends /layout
    
block content
  h1.hideondisconnect#section Main Menu
  h2.hideondisconnect#matchname= matchname
    
  div.hideondisconnect#content
    div#help
    ...
```
layout.pug:
```
doctype html
html(lang="en")
  head
    meta(name='google', content='notranslate')
    meta(http-equiv='content-type', content='text/html;charset=utf-8')
    title=title
  body
    div(style='display: none;' theme='#{theme}' menuautoopen='#{menuautoopen}')#pmmui
    include /menu
    include /disconnect
    block content
```

menu.pug:
```div.hideondisconnect.no-print#jqxMenu
  input(type='hidden' value="#{pmmmatchtype}")#menu_matchtype
  ul
    li File
      ul
      ...
```

**Comment by katsew** [comment]
@jcwren 

you can write interpolation like template string.
```
doctype html
html(lang="en")
  head
    meta(name='google', content='notranslate')
    meta(http-equiv='content-type', content='text/html;charset=utf-8')
    title=title
  body
    div(style='display: none;' theme=`${theme}` menuautoopen=`${menuautoopen}`#pmmui
    include /menu
    include /disconnect
    block content
```

you can see the changes here: https://github.com/pugjs/pug/issues/2305

**Comment by ForbesLindesay** [comment]
This should work fine.  Are you sure you're using 2.0.0-alpha6?  Try deleting node_modules and re-installing.

**Comment by jcwren** [comment]
Definitely am running 2.0.0-alpha6. After making the changes suggested by @katsew, and a couple of others where #{xx} notation was used in interpolation, I got it working. Thanks :)

I wish the nomenclature was standard everywhere. Where I previously had "p #{matchname}", I had to change that to "p= #{matchname}" to get it to work with pug. Sometimes you need backticks, sometimes you don't. I'd have no problem with having variables always requiring #{xx} or ${xx}, and if you don't want the #{ or ${ to trigger interpolation, then you use \$\{ or whatever.

**Comment by ForbesLindesay** [comment]
I'm pretty sure `p= #{matchname}` does **not** work.  I'm also very sure that the fixes described by @katsew, whilst correct and fixing some issues with your code (We deprecated support for interpolation in attributes.  Attributes are just plain JavaScript values so you can do this even more simply) did **not** fix the issue you were having with `include`.  The samples of input and output you provided did **not** happen when using pug 2.0.0-alpha6.  Please be more careful in future to make sure your examples actually match the code you used.

@katsew: There's no need for interpolation at all here.  We should be un-teaching the advanced feature of jade interpolation that was not needed and no longer exists.  We should avoid teaching the advanced feature of js interpolation in template literals unless people actually need it:

```
doctype html
html(lang="en")
  head
    meta(name='google', content='notranslate')
    meta(http-equiv='content-type', content='text/html;charset=utf-8')
    title=title
  body
    div(style='display: none;' theme=theme menuautoopen=menuautoopen)#pmmui
    include /menu
    include /disconnect
    block content
```

**Comment by jcwren** [comment]
Sorry, you are correct, in one respect, and wrong in another.

I had to change 'p #{error.stack}' in jade to 'p= error.stack' in pug. 'p ${error.stack}' nor 'p `${error.stack}`' worked, not 'p= #{matchname}' as I had indicated.

The examples I provided are exactly what I was using, with the extraneous markup in the middle replaced with '...' to drastically shorten the example. I'm unclear whether #{} nomenclature should work or not, but this does indeed work under 2.0.0-alpha6.

$diff utils.jade utils.pug
27c27
<         | <b>Reload Unscored Match</b> -- Reloads the '#{matchname}'
---
>         | <b>Reload Unscored Match</b> -- Reloads the #{matchname}

**Comment by ForbesLindesay** [comment]
We never use `${` for interpolation in pug.  We always use `#{` for escaped js interpolation.  We do not support using `#{` when the value is already a JavaScript expression, because in these situations you can simply omit the quotes around your value.  Since these places are JavaScript expressions, and JavaScript now has new types of strings called "template literals" that support interpolation, you can also use those within JavaScript expressions that are in pug templates.

I'm pretty much certain that `p #{error.stack}` will do exactly the same thing as `p= error.stack`.  I personally prefer the latter approach most of the time, but you can see the latter syntax in some of our test cases: https://github.com/pugjs/pug/blob/master/test/cases/each.else.pug


There's no way in hell you included a "menu.pug" file with the code:

```
  input(type='hidden' value="#{pmmmatchtype}")#menu_matchtype
  ul
    li File
      ul
      ...
```

and got the string:

```
   div.hideondisconnect.no-print#jqxMenu
   input(type='hidden' value="#{pmmmatchtype}")#menu_matchtype
   ul    
     li File 
       ul
       ...
```

For a start, where did that extra div come from?  Secondly, we fixed an issue in pug-alpha4 where excluding the extension resulted in the literal text being included, rather than compiled.  This is clearly what you were experiencing, which leads me to conclude that you were initially using an older version of pug, and later updated (perhaps without realising you had done so).  The fact that you say you haven't changed anything (other than some unrelated attribute interpolation) leads me to conclude that my initial instinct was correct.

**Comment by katsew** [comment]
@ForbesLindesay 

>   We should avoid teaching the advanced feature of js interpolation in template literals unless people actually need it


```
```
