### ISSUE TITLE
Why compile/renderFile reads file synchronously?

### ISSUE THREAD

**Issue by urugator** [pugjs/pug#2361]
I just started with pug and to my surprise, API does not require me to pass a callback as is customary in node world. So I checked the code and found out that files are handled synchronously.
What is the reason behind that?

**Comment by ForbesLindesay** [comment]
Discussed at length elsewhere.  To summarise:

All files are read at compile time.  It doesn't matter if the performance is a few milliseconds worse at compile time.  It only matters how slow it is at runtime.  There's therefore no point making it asynchronous at compile time.

You do need to make sure you either use `pug.compile/pug.compileFile` or pass `{cache: true}` to the render method so that you're not compiling on every single request.  Express should do this automatically for you if you set NODE_ENV=production.

**Comment by urugator** [comment]
In my case, compile time is a first request for a template that has been changed ... to me, that's a subset of runtime and how often this happends is really app specific. Having a single request delayed because of loading a file is not a problem, however having other requests processing blocked doesn't seem right to me.
So I don't agree, that there is no point of making it asynchronous.
However I don't have any metrics to really say that there is some noticable difference and I probably don't care until it became a problem.
