### ISSUE TITLE
pug foo.jade not working?

### ISSUE THREAD

**Issue by exzhawk** [pugjs/pug#2372]
OS: Windows
pug-cli version: 1.0.0-alpha1

Run pug foo.jade does nothing, and no file is generated.

**Comment by ForbesLindesay** [comment]
This issue seems to be about the pug CLI rather than the core pug library.  To help keep this repo focused, it would be great if you could re-post this issue to [pug-cli](https://github.com/pugjs/pug-cli) so someone can look into it.  Make sure you include as much detail as possible in your issue.

Sorry for the inconvenience.
