### ISSUE TITLE
Pug does not evaluate paceholders at tag argument

### ISSUE THREAD

**Issue by niksonleonard** [pugjs/pug#2402]
Using Express 4, it claims to replace jade for pug.
When I put a placeholder as a tag argument it does not inflate with value anymore.
The first placeholder, #{name}, is replaced nicely but  #{_id} and #{name} does not.

```

block content
  h3 #{name}

  .challenges(ng-controller='InstitutionDetailController as Ctl',ng-init="Ctl.institution._id='#{_id}';Ctl.getChallenges()")
    .row
        .col-xs-2
          - if (coverData.url)
            .form-group
              img.thumbnail(src='#{name}', width="100%")

```

Thanks!

**Comment by rodolph66** [comment]
I have experienced the problem. The following code used in one of my projects (copied into HTML2Jade for verification then pasted here) with jade files works as expected. However when I change to pug the last two lines evaluates properly but "/books/#{book.id}" does not. I had to revert back to jade to get it working properly again. Is anyone looking into this? I thought it was just a change of name with no impact on functionality...!!!!

- var books= [{"name": "book1","id": "f275"},{"name": "book2","id": "c636d" }];

table.table.table-striped
  tbody
    each book in books
      tr
        td(style="width: 50px;")
          a(href="/books/#{book.id}") 
        td= book.name
        td= book.id

**Comment by TimothyGu** [comment]
@rodolph66, Pug is *not* a drop-in replacement for Jade, since Pug releases start at 2.0.0 while Jade is ≤2. See https://github.com/pugjs/pug#rename-from-jade for more information. HTML2Jade tool is outdated unfortunately.

**Comment by rodolph66** [comment]
Hi Tim. The impression from what was mostly written about pug on the net suggests that, more or less, pug would function as jade, perhaps until the next release. I have already adopted pug in my work and would like to continue so when and were it applies. The above mentioned, perhaps, glitch, was the only issue I encountered so far. Unfortunately due to the lack of documentation on pug and the ubundance of it for jade I was unable to find a work around to the above mentioned issue. I will continue the search or perhaps wait for the release of a more extensive pug documentation. Thanks for your quick reply .

**Comment by TimothyGu** [comment]
As mentioned in the issue referenced in README, simply using JavaScript expression will solve the problem. In your case it would be `href='/books/' + book.id`.

**Comment by rodolph66** [comment]
Oh...man..!!! sometimes things get so entangled in your mind that you miss the quickest and easiest solution. Thanks a lot for that. I did try a lot of iterations but for some reason I missed the most obvious. I have already did the necessary amendments and I'm all "pug" again!!! Thanks again...

**Comment by lucaswelander** [comment]
@TimothyGu That should be added to the documentation, because coming from **Jade** you would make these mistakes as I did and that is why I ended up on this issue.

I think that you do not think of this simple solution by using JavaScript expression because of the odd behaviours. Below is an example which all three would generates the correct string.

_**Jade**_
`li: a(href='/books/#{book.id}') My book`

**_not true Pug_** (coming from jade when realising #{var} inside tag doesn't work)
`<a href='/books/#{book.id}'>My book</a>`
but this line actually works great within your pug template which made me think that this was the way to do it something, before I knew better(after I read this thread i.e)

_**True Pug**_
`li: a(href='/books/' + book.id) My book`

I do not think that you've done wrong, it's just that many people come to pug after being introduced to Jade which makes these errors come up. Even suggestions I found on the web says that you can always do the **not true Pug** version, which makes it incredibly difficult to get out of your "jade/pug" thinking to get things right. Maybe an link form documentation or something that makes it to find this issue.
