### ISSUE TITLE
"pug"  as the name and logo

### ISSUE THREAD

**Issue by ceyhunkerti** [pugjs/pug#2413]
I've been recently thinking to use jade and came across the name and logo change issue.
To be sincere i did not like the name and the new logo and seen other people like me on the net. 
It is mentioned in couple of issues before but i' have to say it again here. 

Can you guys please make a poll both for name and logo?

**Comment by DeadCham7** [comment]
I like pug. Why the f not? I would've like it better if that pug was pink pug. Who cares if the pug is not your favorite name and logo. I would've didn't care if they came up with some stupid name as long as it does not offend me. I like pug template engine itself.

Contributors here already spent their good time and effort to move on to pug. Do NOT make them look stupid.

**Comment by TimothyGu** [comment]
Legal issues are very important issues for us (and should be for everybody), and need to be dealt with sensitivity. We internally have considered a wide range of options for the name of the project, and the name "Pug" is not arbitrarily chosen. We want Pug to be fun and dependable (like pugs), and the name "Pug" ended up being the best candidate.

Another reason why we didn't hold a public referendum for the name was to preserve the availability of the package name on npm. If we end up with five possible names, we don't want other people to claim that name and then demand money for it once the name was chosen; nor do we want to "sit" on the package names ourselves because it is against the [npm Code of Conduct](https://www.npmjs.com/policies/conduct).

If this sounds like corporate BS to you, remember that it is and has always been. We are just forced to play this game in order to keep this project alive.

The logo is an entirely different issue. After securing the rights to use npm package name, we have [public requested](https://github.com/pugjs/pug/issues/2189) logos and designs for our new branding. In fact, our final selected design was made by one of the contributors in that ticket, and nobody can deny that our selection process was totally transparent, though people do hold different opinions on the matter.

Either way, the ship has already sailed. We have dedicated enough time on bikeshedding, and please let us get back to where work is necessary, like our [new website](https://github.com/pugjs/pug/issues/2410).

**Comment by ceyhunkerti** [comment]
Thanks a lot for the answer and sorry for taking your time.
Jade/pug is the best templqting engine. Thanks again..
