### ISSUE TITLE
why remove interpolation in attributes???

### ISSUE THREAD

**Issue by vontio** [pugjs/pug#2434]
link: `https://github.com/pugjs/pug/issues/2305`

We removed support for interpolation in attributes since it was unnecessarily complex in implementation and tended to delay users learning that they can just use any JavaScript value in place of attributes

**Comment by ForbesLindesay** [comment]
You've answered your own question :smile:

**Comment by vontio** [comment]
Hi
I am new to jade,  for a new user I think keep code consistence is more easier to understand.
User does not to care which part is in attributes,  white part is not.

+1 for interpolation in attributes

**Comment by ForbesLindesay** [comment]
It's better that you spend an extra 5 minutes to learn how to do this properly up-front.  It would save hundreds of "How do I do X in an attribute" question.  Now the answer is pure and simple: attributes are just JavaScript expressions.

**Comment by arxpoetica** [comment]
Wow. Stunning that this was removed in favor of someone's "correct implementation" advice. The former *WAS* correct implementation. This is just tawdry opinion. Makes me mad. :(

**Comment by ForbesLindesay** [comment]
There was already inconsistency in the language.  We had interpolation in two different places (plain text and attributes).  The two behaved completely differently:

 - in plain text, interpolation is always escaped if you use `#{}` and not if you do `!{}`
 - in attributes, interpolation is never escaped, but the entire attribute is escaped unless you use `!=`.

This makes it easy to write things like:

```pug
a(href!="#{path}?do=not&escape=this")
```

which looks safe (because normally `#{path}` would be escaped) but is actually extremely dangerous because `#{path}` is not escaped in attributes.  There's no easy way to mitigate this problem.

The other inconsistency is that we do not support interpolation in any of the other locations that JavaScript expressions occur.   e.g.

```pug
ul
  each foo in str.split('#{separator}')
    li foo
```

will not do what you might expect it to.  Rather than encouraging people to think they need interpolation in JavaScript expressions everywhere, it seems much better to teach people how to use JavaScript in attribute values.  For 90% of the cases I've seen, this just means people will be able to type 5 characters fewer per attribute.

**Comment by arxpoetica** [comment]
I see, fair enough.

My last nitpick is that this ought to be documented better in the interpolation section: http://jade-lang.com/reference/interpolation/. It took me quite some time to find this ticket/issue, and not until your explanation above did it make any sense.

Thx for your patience.

**Comment by ForbesLindesay** [comment]
Yes, this could be better documented.  In our defence, interpolation within attributes has **never** been documented.  i.e. anyone who used it was using an un-documented feature.

**Comment by supervova** [comment]
Forbes, can you help me too?  gulp-pug does not deal with ES6 template strings. What should be right alternative for this?

    script(type="application/ld+json").
      {
        "@context": "http://schema.org",
        "@id": "#{site.home}/#organization",
        "@type": "Organization",
        "name": "#{company.name}",
        "description": "#{company.businessDescription}"
      }

**Comment by ForbesLindesay** [comment]
In that location you would still use pug interpolation as you have always been using, since the body of that script tag is not a JavaScript expression in pug, it's plain text.  What you've written should work fine.

**Comment by supervova** [comment]
Thanks
