### ISSUE TITLE
What is the status - in summary - of Pug at present.

### ISSUE THREAD

**Issue by markcollinscope** [pugjs/pug#2453]
Dear All,

I'm actively using Jade/Pug at present.
I previously upgraded to Pug however reverted to Jade 1.11.0 due to lots of problems.
However J1.11 has a few problems too.

Question:
1. Is the most recent release of Pug stable enough to use?
2. Is there a place to report bugs with J1.11.0? And is it worth bothering?
3. Is there a clear description of what one needs to change to upgrade from J1.11 to latest Pug - anywhere?

Many thanks,
M.

**Comment by TimothyGu** [comment]
> Is the most recent release of Pug stable enough to use?

Yes, but because there are multiple incompatibilities between Pug and Jade, I wouldn't recommend using it if you didn't spend time ironing those things out (which can get hairy for a lack of proper tooling).

> Is there a place to report bugs with J1.11.0? And is it worth bothering?

If your bug is fixed in Pug but present in Jade, it's most likely that bug has been reported already.

> Is there a clear description of what one needs to change to upgrade from J1.11 to latest Pug - anywhere?

There is a list of incompatibilities in #2305. I'm trying to add several [pug-lint](https://github.com/pugjs/pug-lint) rules that will help with the migration process but the work has not been finished yet.

**Comment by PascalPencil** [comment]
So should we start a project with pug or jade?

**Comment by ForbesLindesay** [comment]
If you are starting a new project, use pug.

**Comment by PascalPencil** [comment]
@ForbesLindesay I checked the graph and development seems to have slowed a bit?

**Comment by markcollinscope** [comment]
@TimothyGu thanks for your answer. If you could keep us updated on this thread that would be a great help.
