### ISSUE TITLE
Issues with option element on select tag

### ISSUE THREAD

**Issue by Memolition** [pugjs/pug#2465]
1.- When creating the next select, pug adds an empty option element `<option value="? undefined:undefined ?"></option>`  and shows it as default

```
select
  option(value="1") Male
  option(value="2") Female
```
2.- When adding `selected` attribute to any option it would be ignored.

**Comment by ForbesLindesay** [comment]
I'm pretty confident we don't do this.  Either submit a pull request with a failing test case (see https://github.com/pugjs/pug/tree/master/test/cases and add a .pug file and a .html file) or try asking on stack overflow.  You may also want to check by viewing the actual raw HTML that's generated rather than relying on Chrome's web inspector.  It may be that you're HTML is not valid and chrome is messing it up somehow.
