### ISSUE TITLE
Pug filters with express

### ISSUE THREAD

**Issue by omgimanerd** [pugjs/pug#2529]
It isn't clearly documented how to use pug filters with the express framework. Do we need to modify
```
app.set('view engine', 'pug');
```
https://expressjs.com/en/guide/using-template-engines.html only tells us how to use Pug as the template engine, but not how to apply the filters.

**Comment by omgimanerd** [comment]
Way too hard to find.
https://groups.google.com/forum/#!topic/express-js/LVzY5S_ZhwA

**Comment by TimothyGu** [comment]
There are two types of filters: JSTransformers and custom filters. See [filters documentation](https://pugjs.org/language/filters.html) for more info. For most cases, simply installing `jstransformer-<filter>` through npm will allow you to use the filter in a template. If you want to use a custom filter, set `app.locals.filters` to an object like [this](https://pugjs.org/language/filters.html#custom-filters) would allow you to use it.

**Comment by omgimanerd** [comment]
I was looking for how to use a custom filter, I had code that looked like this:
```
module.exports = {
  filter1: function (text, options) {...},
  filter2: function (text, options) {...}
};
```
And I did:
```
var filter = require('./filter');
```
I didn't know that you had to put
```
require('pug').filters = filter;
```
after setting the view engine, which was documented in the link above. Although it seems app.locals.filters works as well, this is not clearly documented.

**Comment by TimothyGu** [comment]
It's not recommended any more to use the `require('pug').filters` method (which is why it's often dangerous to use documentation written for older versions). The option `filters` is pretty well documented at https://pugjs.org/api/reference.html#options, but I guess it's not too clear how `app.locals` and `res.locals` work with Pug options. [Documentation](https://github.com/pugjs/pug-en/blob/master/src/api/express.md) welcome.
