### ISSUE TITLE
extending variable

### ISSUE THREAD

**Issue by Turqueso** [pugjs/pug#2531]
I'm trying the following, but I can't get the variable to extend. Is it possible? am I using this wrong?

```
// layout.pug
doctype html
html(lang="en")
  head
    block title 
      title Title
  block vars
    body(class='#{body}')
    div #{body}
```

```
// index.pug
extends layout.pug
block title 
    title My new title
block append vars
  - var body = 'index'
```

result:
```
// index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>My new title</title>
  </head>
  <body class="#{body}">
    <div></div>
  </body>
</html>
```

**Comment by ForbesLindesay** [comment]
Try:

```pug
// layout.pug
doctype html
html(lang="en")
  head
    block title 
      title Title
  block vars
  body(class=body)
    div #{body}
```

The way you were doing it was putting the vars at the **end** of the resulting template, i.e. defining them after they were being used.  You also can't use `#{...}` syntax in attributes anymore, although the good news is that you can use **any** JavaScript expression.

If you wanted to, you could also write `div= body` instead of `div #{body}`

**Comment by Turqueso** [comment]
Just to conform it works!. So, for extends, indentation should start at same level has `block` so variable get defined at beginning, right? Should this be in the docs?

**Comment by ForbesLindesay** [comment]
You could alternatively have used `block prepend` to add the variables to the start of the block.  The point is that by indenting, you make the body tag **part of** the block.  That way append goes after the content, prepend goes before the content.  By not indenting, you make the block default to being empty, and therefore appending just inserts it directly after the `block` keyword.

Very much the same thing is going on with the `title` block, you can experiment with what happens when you append/prepend some text to each block.

**Comment by Turqueso** [comment]
@ForbesLindesay makes much more sense now, thanks a lot for taking your time explaining!
