### ISSUE TITLE
where's  jade ? what the hell going on? 

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [pugjs/pug#2564]
# [http://jade-lang.com/tutorial/](http://jade-lang.com/tutorial/)

**Anybody can tell me what happened?**

**Comment by AlexanderDolgan** [comment]
Project Rename ¶

Due to a trademark issue, the project name has been changed from “Jade” to “Pug” in conjunction with the release of Pug 2. This also means that we have changed the official supported file extension from .jade to .pug. Although .jade is still supported, it is deprecated, and all users are encouraged to transition to .pug immediately.

**Comment by TonyPythoneer** [comment]
The readme and official document had clearly explained.
