### ISSUE TITLE
bug -> issue with conditions and cases when variables are concerned

### ISSUE THREAD

**Issue by okeniiawak** [pugjs/pug#2595]
I am encountering issue that is kinda dealbraking. I cannot understand what is the cause. Am I missing this. Look carefully to 2 snippets below:

Works:

```
    - var x='y'
    h1=x
    if x === 'y'
        h1 hi!
```
prints **y** and **hi!**

Doesn't work:

```
    - var x='{{@myvar}}'
    h1=x
    if x === 'y'
        h1 hi!
```

prints **y** but doesn't print **hi!** (If statement doesn't work all of the sudden!)

Why is that? The fact that it returns "y" from variable x using "h1=x" in both prooves that the variable I am getting from framework (f3) works (what is doing is making a php echo). But it doesn't work in conditional statements and it also doesn't work in cases.

Any ideas?

**Comment by ForbesLindesay** [comment]
Pug is being used to generate HTML here, before your framework is applying the variable replacement.  In this example it would first generate:

```html
<h1>{{@myvar}}</h1>
```

Notice how the variable still hasn't been replaced, so pug compares the literal strings (`'{{@myvar}}' === 'y'`).  Since the literal strings don't match, it doesn't render the body of the `if` statement.


Then as a second step, your framework process the variable replacement and outputs:

```html
<h1>y</h1>
```

You have two options for ways to solve this.  Without knowing anything about the specific framework you're using I can't advise you as to whether these will work.  You may be able to get more help with this on stackoverflow.com

1. You could figure out how to pass the values of your variables into put as `locals`.  This lets you use the full feature set of pug in the way it's meant to be used.  Your example could then look something like:

  ```pug
  - var x=myvar
  h1=x
  if x === 'y'
      h1 hi!
  ```

2. You could use pug purely to generate HTML and then use the features of your framework of choice to implement conditionals, loops, etc. in the resulting html.
