### ISSUE TITLE
How to add script tag within a script?

### ISSUE THREAD

**Issue by terencechow** [pugjs/pug#2609]
I have express using pug as a view. My index.pug has the following:

```
script(type='text/javascript').
      window.__DATA__ = !{payload}
```

where payload is a json object. It has been stringified in the render function of express:

```
res.render('index', {
    payload : JSON.stringify({
           "anExample": "<script></script>"
     })
  })
```

When my Json object has `</script>` it terminates my `window.__DATA =` function early due to the ending script tag. How can I prevent this from blowing up my page? Is this a limitation of Pug or Express or the browser?

**Comment by ForbesLindesay** [comment]
This is a limitation of JSON.stringify, which is not designed to be used to generate JavaScript liberals to inline in scripts that are inclined in HTML.

You should install the js-stringify module from npm then pass `{stringify: require('js-stringify')}` as one of your locals.  Instead of JSON.stringify outside the template, use stringify as part of your interpolated expression.  It is important to do the stringify as close as possible to the interpolation because not properly escaping (e.g. Using JSON.stringify instead of js-stringify) would be a security problem when used with the `!` unespacex pug syntax.  By doing the two close together it's easier to check you're escaping it at a glance.
