### ISSUE TITLE
Load layout in variable

### ISSUE THREAD

**Issue by burawi** [pugjs/pug#2616]
What if we could do this:
```javascript
var pug = require('pug');

var layout = new pug.Layout('./layout.pug');
var html = layout.render('./page.pug');
```
This can seem useless in small projects but when a project start getting more in complexity it would help us to avoid lines like this:
```
extend ../../views/layout/layout.pug
```
And it helps in mantainabilty

**Comment by adewalegeorge** [comment]
I second this considering I'm using Pug on a large scale project and this would have been a nice to have

**Comment by ForbesLindesay** [comment]
To avoid the `../../../` etc. you can add a `basedir` option and then use `extend /layout.pug` instead.

Making pug files have a clean API prior to extends/include is something that's part of my long term plan for pug.  I want to enable performance optimisations like compiling layout files once and re-using them.  I also want to enable limited forms of dynamic extends and dynamic includes.  All of which is to say I'm definitely thinking about it.

The proposed API is actually interesting, because the layout object could potentially cache the compiled child templates, allowing reasonably efficient rendering of the same child template for two or more different layouts.

**Comment by burawi** [comment]
So we'll see it soon ?

**Comment by burawi** [comment]
I did it!
Check out this repo:
[https://github.com/burawi/pug-layout](url)
