### ISSUE TITLE
Angular 2 bindings causes template parse errors

### ISSUE THREAD

**Issue by vadimzham** [pugjs/pug#2627]
When you trying to add several bindings to Angular 2 template without commam you will get template parse errors. Below example:
```<div [(ngModel)]="filter.concludedStart" [locale]="en"></div>```

Most oblivious convertion below:
```div([(ngModel)]='filter.concludedStart' [locale]='en'```

But you MUST to use comma(else you will get template parse error:
```div([(ngModel)]='filter.concludedStart', [locale]='en'```

Thats terrible. Please fix this.

**Comment by jbsulli** [comment]
Hm, it seems the lexer assumes there is still JavaScript after "filter.concludedStart". The problem is located here: https://github.com/pugjs/pug-lexer/blob/master/index.js#L1070

The square bracket for `[locale]` passes the isPunctuator() test. It would seem Jade doesn't currently work well with Angular 2 bindings.

**Comment by jbsulli** [comment]
Looks like this is a known issue. See https://github.com/pugjs/pug/issues/2223.

**Comment by ForbesLindesay** [comment]
There is no good solution to this.  Adding commas is not a sufficient hardship for angular users to merit breaking things for all non-angular users.
