### ISSUE TITLE
Multiline code for i18n

### ISSUE THREAD

**Issue by ddosoff** [pugjs/pug#2656]
I read many closed issues about multiline support. It seems that authors do not understand why it should be implemented.

Internalization is a complex issue. When you have a 10 languages you begin to understand why GNU gettext is much better then JSON with values as translations.

You should be able to write multiline English text and pass it to gettext function. Than you could compile templates to Javascript and use GNU xgettext utility to extract base language keys. Please believe me this way is much better, then inserting json keys instead of text into templates. That's why multiline code support should be implemented.

We can use traditional javascript multiline strings:

```
p = gettext(`My text for translation
could be long long long... %(arg1)s!`, {arg1: 'val..'})
```

**Comment by ForbesLindesay** [comment]
I fully intend to add support for multi-line JavaScript expressions in the near future.  However, this issue is worded as a negative rant, not a constructive feature request, so I will be closing it.

In future, please stick to:

1. Explain the feature you want
2. Explain why the feature is needed

And skip:

1. The bit where you cast aspersions on what the authors do/don't understand.

This is a question of priorities, not a question of whether or not we want to support the feature.
