### ISSUE TITLE
Mixin attribute with != operator

### ISSUE THREAD

**Issue by kylekatarnls** [pugjs/pug#2660]
Hi,

I get `<a></a>` for the both following templates:

```pug
mixin link()
  a
+link()(class!="<")
```
or:
```pug
mixin link()
  a
+link(class="<")
```

But I get an error with:
```pug
mixin link()
  a
+link(class!="<")
```

It seems the first paretnheses expect `=` but not `!=`.

If you think it's relevant the third syntax would be valid, I can submit a pull request for that.

**Comment by ForbesLindesay** [comment]
The problem is that it would be valid to pass a Boolean expression like that as the first argument to a mixin.

**Comment by kylekatarnls** [comment]
Indeed. So I would say, the best practice would be to always keep the argument list `()` even if empty. As the attribute name detection can be ambigous (`myVar=true` could also be an expression that assign true to `myVar` then return `true`:

```pug
mixin link(_isAdmin)
  if _isAdmin
    strong Admin
  else
    | User
+link(isAdmin=user.isAdmin())
=doSomethingWith(isAdmin)
```
Here we always get `User` since isAdmin is interpreted as an attribute. You have to split in two lines to get the "arguments" behaviour:
```pug
- isAdmin=user.isAdmin()
+link(isAdmin)
```
And the reverse is also ambigous:
```pug
- checked = true
+link(checked)(checked)
```
I would say finally the attribute detection is not so usefull. It could be: first parenthesis is always the arguments list. All following parentheses are attributes. Because there are many expressions both valid for arguments or attributes.

**Comment by ForbesLindesay** [comment]
That is how I would generally recommend people use mixins.  However, we have never had an issue opened due to `+link(isAdmin=user.isAdmin())` being mis-interpreted, so I don't think that's a real problem.  Issues caused by either `+link(checked)` or `+link()(class!="<")` are also surprisingly rare.  I would suggest that we leave the behaviour of pug as it is, and just consider adding something to the documentation.

The content of the documentation is at https://github.com/pugjs/pug-en (You can see the resulting documentation at https://pugjs.org/language/mixins.html)
