### ISSUE TITLE
JSPM plugin

### ISSUE THREAD

**Issue by coderfin** [pugjs/pug#2714]
1. I'm trying to create a JSPM plugin to replace [plugin-jade](https://github.com/johnsoftek/plugin-jade).  I'm running into an issue with uglify-js (see screenshot below).  I've noticed that there have been some issues with uglify-js in the past.  Anything you can give me to point me in the right direction would be great.

![screen shot 2017-02-08 at 11 39 02 am](https://cloud.githubusercontent.com/assets/1514172/22751812/3da9a9be-edf3-11e6-849c-3303efd0ce93.png)

2. I've also thought about pulling in [pug.js](https://pugjs.org/js/pug.js) but I'm not sure how that file works.  I can't find a clear example on how to include pug in the browser using that file.  Just adding it to the page doesn't seem to create `pug`.

**Comment by ForbesLindesay** [comment]
If this is a browser like environment, you should compile the templates using node.js, then you won't need anything at runtime.  You should not attempt to run pug through a bundler like webpack/browserify/etc.  We do it for the website so we can use it in the docs, you should not be doing it that way since you should not be compiling pug files on the fly.

**Comment by KoltesDigital** [comment]
It makes sense to precompile `pug` files instead of doing it again and again on the fly. On the other hand, `express`, [this plugin for Aurelia](https://github.com/Craga89/aurelia-jade-viewstrategy) ... render `jade` files on the fly. So could you please elaborate your recommendation?
