### ISSUE TITLE
Beta version not following node-semver

### ISSUE THREAD

**Issue by chrisnicola** [pugjs/pug#2720]
The beta version for pug is written out as `2.0.0-betaX` which causes NPM to think that `beta2 > beta10` when determining how to satisfy a dependency like `^2.0.0-beta2`.

The correct format should be `2.0.0-beta.X` as specified [here](https://github.com/npm/node-semver#prerelease-identifiers)

**Comment by Sjonnie2nd** [comment]
I seconds this:
npm outdated
Package      Current       Wanted        Latest  Location
pug      2.0.0-beta9  2.0.0-beta9  2.0.0-beta11  xxx

even an "npm update pug@2.0.0-beta11 --force -save" fails

**Comment by steve-taylor** [comment]
+1

```
warning "pug-loader@2.3.0" has incorrect peer dependency "pug@>=2.0.0-beta3 <3".
```

**Comment by blacksonic** [comment]
Related issue https://github.com/pugjs/pug-loader/issues/76
cc @ForbesLindesay

**Comment by VitorLuizC** [comment]
+1
This causes me errors in the C9.io environment.

**Comment by AckerApple** [comment]
This issue is a nasty fly!!!!

Let me throw out possible fixes, so that this comment isn't just a complaint:

- Switch using pug-loader for pug-html-loader, if only converting pugs to static html
- Fork this project and all dependent projects and rewrite all the dependencies. HA!

Opinion, I more "blame" pug-loader for using peerDependencies to check against a more than fairly solid templating engine. It's still Jade to my heart. I think the pug logo should have a color with a Jade gem on it.

**Comment by balciseri** [comment]
+1 please fix

**Comment by wmzy** [comment]
I could not run `npm shrinkwrap` success!

**Comment by ForbesLindesay** [comment]
I didn't know this.  The latest release is `2.0.0-beta.12`.  If that hasn't fixed the problem, please open a new issue and I will do my best to fix things.

**Comment by Sjonnie2nd** [comment]
Still have the same issue when doing a "npm update pug --save". 
In stead of updating to 2.0.0-beta.12 it replaces 2.0.0-beta11 with 2.0.0-beta9.
Only a full ununstall and, after that, an install works.
