### ISSUE TITLE
Escaping German umlauts

### ISSUE THREAD

**Issue by kikime** [pugjs/pug#2725]
It seams like I have to manually escape German umlauts (ÄÖÜ and äöü). But when I do that it either escaped the escape sequence or just completely ignores the rest of the "dangerous characters".

**Comment by ForbesLindesay** [comment]
Duplicate of #2704

I think since this keeps coming up, we should add something about it to our documentation on [buffered-code](https://github.com/pugjs/pug-en/blob/master/src/language/code.md) and possibly [attributes](https://github.com/pugjs/pug-en/blob/master/src/language/attributes.md).

Would you be willing to submit a pull request with this help, having read the explanation in #2704.

**Comment by kikime** [comment]
I actually have the meta(charset="utf-8") added. Error in chrome then?

**Comment by kikime** [comment]
Also on the attributes link in the Multiline Attributes paragraph you got your \``` escaping wrong.

**Comment by ForbesLindesay** [comment]
If you have correctly enabled UTF8 and your source file is in UTF8 you do not need to escape special characters like that at all.

**Comment by kikime** [comment]
Well I just fixed it. Didn't save as UTF-8. (Don't know why though).
Sorry for the inconvinience.
