### ISSUE TITLE
include block extends not working

### ISSUE THREAD

**Issue by ScorpioCoding** [pugjs/pug#2732]
**Hi I'm using Atom and  I can't use the functions "include , block, etc"**

**if I use "include" and compile both files**

![001](https://cloud.githubusercontent.com/assets/20724826/23097880/3c30700e-f640-11e6-9bf4-6534d739690c.PNG)

**I compile and then in firefox I get the following**

![002](https://cloud.githubusercontent.com/assets/20724826/23097890/7dd7ba6c-f640-11e6-8d7e-21503b0f5bba.PNG)

**And if I insert the code direct into the base. pug it works**

![003](https://cloud.githubusercontent.com/assets/20724826/23097896/b337d25a-f640-11e6-984c-53e65045858a.PNG)

****Can anybody give me an idea where to look.**
**I've even uninstalled pug and reinstalled it.**
**And using  "block and extends" does absolute nothing****

**Comment by qm3ster** [comment]
1) What version of pug are you using?
2) You only need to compile base.pug, no reason to compile baseHeader.pug separately as well.
3) What does baseHeader.pug look like?

**Comment by ScorpioCoding** [comment]
What does baseHeader.pug look like ...

![004](https://cloud.githubusercontent.com/assets/20724826/23138261/96c74008-f7a6-11e6-82dc-aa6548e148ca.PNG)

**Comment by ScorpioCoding** [comment]
And the current version of pug installed

![005](https://cloud.githubusercontent.com/assets/20724826/23138474/f95709be-f7a7-11e6-97bb-fb2badea2bc6.PNG)

**Comment by ScorpioCoding** [comment]
So I had a look at the output base.html file and this is the issue the baseHeader.pug didn't compile to HTML
So it found the baseHeader include file, inserted it and then didn't compile/convert it to html.
Doeas anybody know why and has a solution

![006](https://cloud.githubusercontent.com/assets/20724826/23138927/517783b0-f7aa-11e6-87ce-21d23442a42c.PNG)

**Comment by qm3ster** [comment]
1. Is [this](https://cloud.githubusercontent.com/assets/20724826/23097890/7dd7ba6c-f640-11e6-8d7e-21503b0f5bba.PNG) base.html?
2. Does it contain anything from `base.pug`? (All I see in the screenshot is what was in baseHeader.pug)
3. Please post text and not screenshots in the future, it is very hard to navigate without search.
## Solution:
You have a circular 'dependence' even when you try to compile just `base.pug`. This is because you use both `include` syntax and `extends block` syntax. `extends block` is for versions of the same page. You can only `extend` one template (with block slots) per compile. For example your some_page.pug could extend layout.pug which would contain a head, a header, a "block content" and a footer.
`include` is for literally including the text of one file within another. This is what you want to be using in your case, since you are including a partial into the page. Remove extends and block from `baseHeader.pug` and it should work. Remember, only compile the page you want to get, not partials.

**Comment by qm3ster** [comment]
# Example
```pug
//- mothership.pug
head
    include head
body
    <nojs google tag manager>
    block body
```
```pug
//- head.pug
meta ...
script ...
link ...
```
```pug
//- layout.pug
extends mothership
block body
    include header
    article.post
        block content
    include footer
```
```pug
//- header.pug
header
    include logo
    nav
        ul
            for val in nav
                li
                    a
```
```pug
//- post.pug
extends layout
block content
    :remarkable
        # Hello
        Dis is post.
    include:remarkable signature.md
```
```markdown
[//]: # (signature.md)

Pls **like** and **subscribe**.
```
et cetera.

**Comment by ScorpioCoding** [comment]
So After playing around with it I got the stupid idea to rename the files to ".jade" extention.
And it works. if I rename my includes to **whatever.jade** it works...stupid no ?
Is this a know issue ?

![007](https://cloud.githubusercontent.com/assets/20724826/23140487/3aa5a83a-f7b2-11e6-8411-02a007640089.PNG)
![008](https://cloud.githubusercontent.com/assets/20724826/23140488/3aa5c568-f7b2-11e6-947e-051e11ae52df.PNG)

**Comment by qm3ster** [comment]
If changing it back and forth really recreates the effect, it must have something to do with another program mangling your files, perhaps based on extension. I would look at your task runner, whoever is grabbing the supporting files for your pug. Might be a frontent/**.jade in there somewhere.
Me, I run pug-cli's pug -w at the moment and I am on 
```console
$ npm list pug
secretpackage@0.0.0 /secret/directory
└─┬ pug-cli@1.0.0-alpha6
  └── pug@2.0.0-beta11 
$ npm-exec pug --version
pug version: 2.0.0-beta11
pug-cli version: 1.0.0-alpha6
$ npm ScorpioCoding -v
3.10.10
```
The last one actually gives you npm version as you can see. You should globally install npm-exec if you like locally installing bins against their request. (I know I do :smile: )
Anyway, my testing has shown the following behavior:

`include header.pug` looks for `header.pug`
`include header.jade` looks for `header.jade`
`include header` looks for `header.pug`, does **not** look for `header.jade` afterwards
`include header.jeff` (random extension) looks for `header.jeff` then includes it as **plain text without parsing**. Which is what happened to you?
So, jade was not in any way special for file matching (I thought it looks for it when there is no extension, but I was unable to reproduce it right now. The behavior of that when it was happening was quite hilarious - it would go from jade to pug when a pug file was added in the directory, but it wouldn't go back to jade in the same -w run.
It **is** special in the way that it satisfies the parsed include rather than plain text include rule.
I have no idea how you could have knocked out .pug as an acceptable pug extension in pug. Perhaps it gets mangled by whatever is passing it to pug. Perhaps you (consistently?) spelled it with a letter other than English p, u and g. Please see your real pug version and then reinstall it.

If you can really reproduce this issue, I suggest you look at where pug is plugged in/specified in your pipeline rather than use the depreciated filename.

**Comment by ScorpioCoding** [comment]
dit a npm list pug and got the following error

![009](https://cloud.githubusercontent.com/assets/20724826/23149661/e6950b82-f7ed-11e6-96dc-35bc43ad277a.PNG)

**Comment by ScorpioCoding** [comment]
so I whent and installed everything localy for my project and a screenshot of my package.json file

![010](https://cloud.githubusercontent.com/assets/20724826/23150261/9357135c-f7f2-11e6-8f30-cf852cf6e541.PNG)

**Comment by qm3ster** [comment]
You have `gulp-pug` installed in your globals, you should get rid of that. At most you should have `pug-cli` there.
But the real question: does your project currently work or is there a problem?

**Comment by ForbesLindesay** [comment]
This is almost certainly an issue caused by having incorrect versions of packages installed.

**Comment by ForbesLindesay** [comment]
@ScorpioCoding please use GitHub Flavoured Markdown to include code in issues/comments in future.  Do not post screen shots of code.

**Comment by ScorpioCoding** [comment]
Sorry been of the grid for a day...
OK
So you're say I should install -pug-cli globaly and localy gulp-pug or what ???
Sorry what is GitHub Flavoured Markdown ??
I'm going nuts with all these technologies, keeping up is the hardest. 
I'm trying my utmost best to keep up

**Comment by ScorpioCoding** [comment]
Sorry forgot to answer your question ...
No it stil doesn't work I can only include JADE files and PUG get included but don't compile.

**Comment by ForbesLindesay** [comment]
http://lmgtfy.com/?q=GitHub+Flavoured+Markdown

If you are using gulp-pug, you should install gulp-pug locally, and install nothing globally.  If you are using gulp-pug and struggling to get it set up correctly, you should post your questions on https://github.com/pugjs/gulp-pug

**Comment by ScorpioCoding** [comment]
So pug-cli globaly and gulp-pug localy
