### ISSUE TITLE
How to use "inline" HTML

### ISSUE THREAD

**Issue by LuisUgalde** [pugjs/pug#2759]
I've been trying for quite a while now and can't get pug to render "inline" HTML. Say for example I have a Javascript variable I want to use:

`public example: string = <p>List</p><p><ul><li>item1<br></li><li>item2<br></li></ul></p>`

How can I get pug to interpret this variable without displaying the HTML tags in my template?

Putting the attribute in between `{ }` obviously doesn't work, I've tried with `#{ }` and that didn't work either, any help is greatly appreciated.

**Comment by jbsulli** [comment]
Because you're using a variable, you need to do something like the following:
```pug
div!= string
//- or
div the following is html after this text !{string}
```
**Remember:** Unescaped buffered code can be dangerous. You must be sure to sanitize any user inputs to avoid cross-site scripting (XSS). 

That is why you need to use the exclamation mark... so most people don't do dangerous stuff without knowing about it.

**Comment by LuisUgalde** [comment]
Turns out it had something to do with Angular 2 and I had to pass the attribute through a [innerHtml] property.

`div([innerHtml]="example")`
