### ISSUE TITLE
Classname throw an error

### ISSUE THREAD

**Issue by josueadelima** [pugjs/pug#2769]
UIkit framework version 3 use this type of classnames: `.uk-width-@xl` I made a test on w3c html validator and it seems to be a valid classname, the only way to use it with pug is `div(class="uk-width-@xl")`.

It would be nice to write just `.uk-width-@xl` but throws an error.

**Comment by ForbesLindesay** [comment]
I've not seen `@` used in class names anywhere else.  If we added this as an option we loose the ability to reserve `@` for future use in pug syntax.  The workaround is also reasonably simple, so I don't think we should add support at this time.

**Comment by josueadelima** [comment]
Hi @ForbesLindesay,

I respect your decision, but I don't I believe is right, for two main reasons:

1.- You are saying you haven't seen `@` used in class names anywhere else, I haven't too, until now.., but is just experience of two people, experience should be avoid when posible in this type of decisions.

2.- `@` is a valid character for a classname, so it  shouldn't be consider for pug syntax.

Regards

**Comment by smikitky** [comment]
Yes a valid class name can contain the character `@` and even `{`, `#`, `(` and so on. But that of course doesn't mean you can write them verbatim in standard CSS files. You have to escape them. See: https://mathiasbynens.be/notes/css-escapes

And see [this fiddle](https://jsfiddle.net/m4sqxr67/).

So you may want to write `div.uk-width-\@xl` instead, but escaped CSS classnames described above does not seem to be compatible with the grammar of Pug anyway. In CSS `.a\31 b` is a **valid** classname notation which is equivalent to writing `.a1b`. However in pug `.a\31 b` should probably mean a div with the classname `a1` and the text content `b`.

I'd rather not see troubles caused by immaturely-implemented classname escaping. As you already know, there already is an obvious and simple workaround.
