### ISSUE TITLE
Call mixin from another mixin

### ISSUE THREAD

**Issue by minicacristi** [pugjs/pug#2814]
Is there a possibility to call a mixin from another mixin? Composition and specialization of mixins might be very useful.

Maybe even redirect the output of a mixin as an input/argument to another mixin (chaining of mixins).

Thank you,
Cristi

**Comment by jeromew** [comment]
it should be working out of the box. Do you have a specific idea in mind ?

**Comment by minicacristi** [comment]
For example let's consiedr some sort of panels.

**Comment by minicacristi** [comment]
Found how to compose mixins. Thanks for the fast answer.

For example let's consider a variation on panels. Let suppose one would want to create a generic panel mixin which receives some arguments (image, color, text, etc...) and suppose that some type of panels are used more often. One might want to simplify the call to that panel.
`mixin genericPanel(color, text, image, ....)
      ....
mixin dangerPanel(dangerText)
  +genericPanel('red', dangerText, 'danger.png' )
`

This is specialization of mixins. But maybe one would want to chain them. For example the text in the panel might have some special formatting (italics, links etc) and one might call it:
`+dangerPanel(+dangerParagraph('This api is deprecated!'))`

Is this possible?

**Comment by minicacristi** [comment]
I imagine that using plain JavaScript functions might work, but it feels hackish.

**Comment by jeromew** [comment]
Well

    mixin dangerPanel(dangerText)
      +genericPanel('red', dangerText, 'danger.png' )

is already possible and should be working out of the box according to me.

you also have dynamic mixins when you don't know beforehand the name of the mixin you want to call

    - var name = "dangerPanel"
    +#{name}(dangerText)

but currently I don't think you can have access to the result of the mixin. This kind of makes sense since the mixin outputs formatted html where pug has already done some non trivial things (escaping for example) and it would not be easy to "modify" this.

you also have the notion of mixin blocks that you may want to check out.

cf https://pugjs.org/language/mixins.html

**Comment by minicacristi** [comment]
Thank you jeromew!
