### ISSUE TITLE
“Pug is available in your Web browser’s console!” what does that mean?

### ISSUE THREAD

**Issue by sunq0001** [pugjs/pug#2876]
i tried to type` pug.render('p Hello world!');`   into browser's console, but it doesn't work.
error message: "pug is not defined".  
i don't believe browser can integrate pug. so there must be something missing in the description. 
tutorial has many problems, such as "runtime.js" doesn't exist, and i saw this issue was discussing last year, so far haven't solved yet.

**Comment by TimothyGu** [comment]
> i tried to type` pug.render('p Hello world!');`   into browser's console, but it doesn't work.
error message: "pug is not defined".  

You have to type it in the console of any Pug API documentation page.

> tutorial has many problems, such as "runtime.js" doesn't exist

Where did you see reference to "runtime.js"?

**Comment by sunq0001** [comment]
@TimothyGu 

sorry, maybe i am dumb here as i am new on web programming. 

if i use HTML tag in html file 
<script src=""></script>
web won't recognize "require" as we need `var pug = require('pug') `   

if  i use Express.js
 we will use   `res.render('pug.pug')` but `pug.render()`

could you help to show some demo?  

regarding "runtime.js"
below is written in tutorial

> Be sure to send the Pug runtime (node_modules/pug/runtime.js) to the client in addition to the template that you just compiled.

but actually there is no "runtime.js" file in pug module. 
and this has been mentioned about in issue

[(https://github.com/pugjs/pug/issues/2547)]

it is still open.

**Comment by jcsahnwaldt** [comment]
Pug is available in my Web browser's console. I start Chrome, go to https://pugjs.org/api/reference.html , open the console, and type
`pug.render('p Hello world!');`
Result:
`"<p>Hello world!</p>"`
Cool! Works for me.

**Comment by jcsahnwaldt** [comment]
I copied a bit of code from https://pugjs.org/api/reference.html and https://pugjs.org/js/generic.js, commented out a few lines, and put together a minimal working HTML page / JavaScript snippet that renders pug to HTML in the browser. Tested in Chrome 61 and Safari 11. Download the attached files, remove the .txt extension (sorry, GitHub doesn't allow me to upload .html and .js files), and open pug.html in your browser. It may take a second or two because it has to load a lot of JavaScript, but you should see 'Yay! It worked!'.

[pug.html](https://github.com/pugjs/pug/files/1347532/pug.html.remove-extension.txt)
[generic.js](https://github.com/pugjs/pug/files/1347531/generic.js.remove-extension.txt)

**Comment by sunq0001** [comment]
@jcsahnwaldt  thank you a lot! 
'yay! it worked.' 
i got the point of tutorial.  the pug API can be used in pug API web page. 
and your pug.html works fine too.

**Comment by TimothyGu** [comment]
Seems like the question has been answered. Cheers!
