### ISSUE TITLE
Question: filters in buffered text

### ISSUE THREAD

**Issue by rstacruz** [pugjs/pug#2883]
I'd like to do this:

```
:markdown-it
  = body
```

This obviously doesn't work as what some may think, it treats `= body` as input for Markdown text. However, I want to get the `body` variable filtered through markdown. Is that possible?

**Comment by droooney** [comment]
You cannot do that because all filters are rendered compile-time and cannot have dynamic options or content. Transforming markdown in runtime would be too slow. However, if you really want to achieve that you can always use the transformer itself (`markdown-it`):

```pug
div.markdown-body
  != md.render(body)
```

and in your js code that renders pug just pass `md` as a local or global variable, where `md` is defined as:

```js
const MarkdownIt = require('markdown-it');
const md = new MarkdownIt();
```
