### ISSUE TITLE
Compile error when class name begins with dash followed by number.

### ISSUE THREAD

**Issue by meatcar** [pugjs/pug#2907]
**Pug Version:** 2.0.0-rc.4

**Node Version:** v8.9.1

## Input JavaScript Values

```js
pug.renderFile('input.pug', {});
```

## Input Pug

```pug
.-1u Some Content
```

## Expected HTML

```html
<div class="-1u">Some Content</div>
```

## Actual HTML

```
Error: /usr/src/app/input.pug:10:24

     > 1|       .-1u Some Content
    --------------^
    If a class name begins with a "-" or "--", it must be followed by a letter or underscore.
       at makeError (/usr/src/app/node_modules/pug-error/index.js:32:13)
       at Lexer.error (/usr/src/app/node_modules/pug-lexer/index.js:58:15)
       at Lexer.className (/usr/src/app/node_modules/pug-lexer/index.js:413:12)
       at Lexer.callLexerFunction (/usr/src/app/node_modules/pug-lexer/index.js:1319:23)
       at Lexer.advance (/usr/src/app/node_modules/pug-lexer/index.js:1355:15)
       at Lexer.callLexerFunction (/usr/src/app/node_modules/pug-lexer/index.js:1319:23)
       at Lexer.getTokens (/usr/src/app/node_modules/pug-lexer/index.js:1375:12)
       at lex (/usr/src/app/node_modules/pug-lexer/index.js:12:42)
       at Object.lex (/usr/src/app/node_modules/pug/lib/index.js:99:27)
       at Function.loadString [as string] (/usr/src/app/node_modules/pug-load/index.js:44:24)
       at compileBody (/usr/src/app/node_modules/pug/lib/index.js:86:18)
       at Object.exports.compile (/usr/src/app/node_modules/pug/lib/index.js:243:16)
       at handleTemplateCache (/usr/src/app/node_modules/pug/lib/index.js:216:25)
       at Object.exports.renderFile (/usr/src/app/node_modules/pug/lib/index.js:428:10)
       at Object.exports.renderFile (/usr/src/app/node_modules/pug/lib/index.js:418:21)
       at View.exports.__express [as engine] (/usr/src/app/node_modules/pug/lib/index.js:465:11)
       at runCallback (timers.js:785:20)
       at tryOnImmediate (timers.js:747:5)
       at processImmediate [as _immediateCallback] (timers.js:718:5)
```

## Additional Comments

I'm supporting an applicatin that is using https://github.com/ajlkn/skel as a grid framework, which uses classes like `6u` and `-6u` to designate columns and offsets respectively. AFAIK those are not valid classes according to spec, but they used to work ok with `jade`. 

I'm migrating from `jade` to `pug`, and am running into this compile error. It's pretty show-stopping, re-writing all the views to use a different grid framework would be very painful. We haven't had any rendering issues with any modern browsers due to using off-spec class names.

**Comment by droooney** [comment]
You can use the following syntax:

```pug
div(class="-1u") Some Content
```

**Comment by meatcar** [comment]
That is an option, but we would still have to rewrite a lot of code to do the migration, vs just changing a regexp to allow class names to have numbers after a dash. That wouldn't conflict with any other pug syntax, make the templates less verbose (one of pug's main selling points), and would make some users very happy :)

This is the line in question: https://github.com/pugjs/pug-lexer/blob/035c891823b2193121421dc3db660810deac6b3e/index.js#L406

**Comment by droooney** [comment]
It does sound that it won't hurt anyone and doesn't violate any other syntax. But solving this case would be only a half measure, because technically you can use any unicode character in your HTML class name.

If the syntax should be extended, it probably should allow any characters except for `.`, `#`, `&`, braces, whitespace characters and maybe a couple of other characters that may become a part of the future pug syntax. The id syntax should probably be extended in this case as well.

@ForbesLindesay @TimothyGu any thoughts?

**Comment by jbsulli** [comment]
Please no. Using a dash (or other odd char) at the beginning of a class literal makes it look like there is something strange/fancy going on. Class and Id literals are what make pug so clean and readable. Allowing other characters will make it difficult to parse and understand.

That being said... it looks like we allow one or two dashes at the beginning of classes now??? This is odd... seems like if we are going to allow dashes, allow infinite dashes. Allowing numbers at this point doesn't seem like a big deal. But for funky use cases like this, instead of making the project more convoluted, I think we should point people to how they can write a simple plugin for their use case:

```javascript
const pug = require("pug");

const extendedClassLiteralPlugin = {
    lex: {
        "className": function(lex) {
            var tok = lex.scan(/^\.([_a-z\-0-9][_a-z0-9\-]*)/i, 'class');
            if (tok) {
                lex.tokens.push(tok);
                lex.incrementColumn(tok.val.length);
                return true;
            }
        }
    }
}

pug.render(".-6u Test", { plugins:[extendedClassLiteralPlugin] }, (err, result) => console.log(err || result));
```

This way, future support for these fringe cases is on them and not bogging down the Pug.js team.

**Comment by ForbesLindesay** [comment]
> If the syntax should be extended, it probably should allow any characters except for `.`, `#`, `&`

We don't want to do this because it would prevent us adding any new meaning to any special characters without a full breaking change.  e.g. in the future we may want to use `@` or `$` or `*` for something special.  There are already things missing from this list (e.g. `!`, `=`) so it's really hard to properly maintain.  How about we simplify the requirements in https://github.com/pugjs/pug/blob/926f7c720112cac76cfedb003e25e9f43d3a1767/packages/pug-lexer/index.js#L406 to something like:

```js
var tok = this.scan(/^\.([_a-z0-9\-]*[_a-z][_a-z0-9\-]*)/i, 'class'); 
```

i.e. must have at least one letter or `_` but can have that anywhere in the name.  I think this is probably a lot broader than what's technically allowed in the spec, but browsers tend to be fairly permissive.


We'd then need to replace the two error conditions https://github.com/pugjs/pug/blob/926f7c720112cac76cfedb003e25e9f43d3a1767/packages/pug-lexer/index.js#L412-L417 with one that went something like:

```js
if (/^\.[_a-z0-9\-]+/i.test(this.input)) {
  this.error('INVALID_CLASS_NAME', 'Class names must contain at least one letter or underscore.');
}
```

If someone sends a pull request for this, along with a test case, I'd be willing to accept.
