### ISSUE TITLE
how to use options.self and options.global in pugjs?

### ISSUE THREAD

**Issue by anlexN** [pugjs/pug#2910]
**i want to use node module, but don't understand how to import data in the pug!**
![default](https://user-images.githubusercontent.com/8686739/33113219-41c330ca-cf92-11e7-9d05-a3f387a7b26b.PNG)
![2](https://user-images.githubusercontent.com/8686739/33113220-420df38a-cf92-11e7-9581-8ead45b0c973.PNG)

pug document team , please explain more , example by example!
![3](https://user-images.githubusercontent.com/8686739/33113685-7ae39460-cf94-11e7-85da-efd8e6528590.PNG)

**Comment by ForbesLindesay** [comment]
I have no idea what you are actually trying to achieve here.  If you want to use `self`, you should reference `self.SOMETHING` instead of `SOMETHING` for variables passed in to the template (which are called "locals").  Variables you declare inside the template should just use `var variableName` as normal.  The speedup from using `self` is fairly minimal these days as lots of optimisation has happened since the feature was first introduced.
