### ISSUE TITLE
pug is caching parameter (environment) objects?

### ISSUE THREAD

**Issue by theonlygusti** [pugjs/pug#2923]
**Pug Version:** 2.0.0-rc.4

**Node Version:** 7.4.0

## Input JavaScript Values

```js
app.get('/index', (req, res) => {
  const prompt = 'Input:';
  if (Math.random() > 0.5) {
    const placeholder = 'default';
    pug.renderFile('index', {prompt, placeholder});
  } else {
    pug.renderFile('index', {prompt});
  }
});
```

## Index Pug

```pug
if placeholder
  input(type="text",placeholder=placeholder)
else
  input(type="text")
```

## Expected HTML

Half with placeholder and half without.

## Actual HTML

Most of the time it _has_ the placeholder.

## Additional Comments

I have had problems with pug caching the `{}` (template object? I don't know the right word) in lots of situations.

**Comment by ForbesLindesay** [comment]
I think it's far more likely that this is just Math.random being random and returning a value > 0.5 with slightly higher frequency than you expect.  I suggest rewriting the example to toggle explicitly between two options so that each payload alternates and see if you can reproduce the issue.  If you can, please add a test case (see https://github.com/pugjs/pug/tree/master/packages/pug/test/duplicate-block for an example to copy) that demonstrates the issue.
