### ISSUE TITLE
browserify transform

### ISSUE THREAD

**Issue by coachshea** [pugjs/pug#2930]
**Pug Version:** your version number here
2.0.0-rc.4
**Node Version:** your version number here
9.2.1
## Input JavaScript Values

```js
```

## Input Pug

```pug
include:browserify file.js

or

:browserify
  code
```

## Expected HTML

```html

```

## Actual HTML

```html
Error: The Transform "browserify" does not support rendering synchronously.
    at Transformer.renderFile (/usr/local/lib/node_modules/pug-cli/node_modules/jstransform
er/index.js:320:11)

```

**Comment by droooney** [comment]
Ah, I get it now. This is not really related to `pug`, but rather to the [transformer](https://github.com/jstransformers/jstransformer-browserify). So the issue should be fired there.

But I know what's going on. [jstransformer](https://github.com/jstransformers/jstransformer) requires a transformer to expose a `renderAsync` or/and `render` methods (you can read about them and others by navigating to the link), and the latter doesn't exist in `jstransformer-browserify` because browserify uses streams which are asynchronous. I suggest you suggest there that they expose the syncronous method which can be implemented using [`child_process.execSync()`](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options), for instance.

**Comment by coachshea** [comment]
Thanks again for all your great help. I will close this issue and open one on that repo, including your suggestion.
