### ISSUE TITLE
Pug + react + i18n - custom tag

### ISSUE THREAD

**Issue by fsabreu** [pugjs/pug#2973]
Hi, I'm using pugjs with react and its works great.

But to use i18n I need to put a tag like this <FormattedMessage {... messages.header} />

How can I do that?

Thanks

**Comment by ezhlobo** [comment]
@fsabreu if you are using official way to use pug with react ([pugjs/babel-plugin-transform-react-pug](https://github.com/pugjs/babel-plugin-transform-react-pug) then you can do that this way:

```pug
FormattedMessage(...messages.header)
```

Related discussion: https://github.com/pugjs/babel-plugin-transform-react-pug/issues/37

**Comment by fsabreu** [comment]
I'm using [pug-as-jsx loader for webpack](https://github.com/bluewings/pug-as-jsx-loader)

when I put your code I received this two error:

`Warning: Failed prop type: The prop id is marked as required in FormattedMessage, but its value is undefined`
and 
`Uncaught (in promise) Error: [React Intl] An `id` must be provided to format a message.`

I don't know if this change somethig but I'm using react-boilerplate.

**Comment by ezhlobo** [comment]
@fsabreu then try to use [`&attributes`](https://pugjs.org/language/attributes.html#attributes):

```pug
FormattedMessage&attributes(messages.header)
```

Anyway your issue is related to `pug-as-jsx-loader` project. It actually has the same question in issues: https://github.com/bluewings/pug-as-jsx-loader/issues/3.

If it does not help, I would suggest you to ask this question in `pug-as-jsx-loader` repository.

**Comment by fsabreu** [comment]
@ezhlobo Thank you for your answer. 

I will try that.

**Comment by ezhlobo** [comment]
@fsabreu don't be afraid of asking further questions.
