### ISSUE TITLE
pug-parser versionning

### ISSUE THREAD

**Issue by turpault** [pugjs/pug#2979]
At the time of this writing (March 8th, 12:00 EST), there is a pug-parser 4.0.2 version published in the npm registry, but no release tag for that version exists in github. 

It seems that the npm version 4.0.2 reverts the changes introduced in 4.0.1 (which actually broke our product, but that's another ticket).

Could you add release tags matching the published versions in the npm registry ?

Thank you.

**Comment by Honigbaum** [comment]
Hi, 

same problem here. We had no problems with pug 2.0.0 yesterday - which had pug-parser 4.0.1 as dependency yesterday. Today the dependency is pug-parser 4.0.2 and our product broke: 

`2018-03-09T08:58:51,264] ERROR `line` is not an integer
NodeException:     at Parser.initBlock (/OBI/QA/services/obifrontend_nodejs/node_modules/pug-parser/index.js:156:36)
NodeException:     at Parser.emptyBlock (/OBI/QA/services/obifrontend_nodejs/node_modules/pug-parser/index.js:168:17)
NodeException:     at Parser.block (/OBI/QA/services/obifrontend_nodejs/node_modules/pug-parser/index.js:989:22)` 

Relating to this issue: since pug 2.0.0 was released, the release candidate 4 is broken. It looks like pug-parser was updated, but pug-lexer not.

Thank you.

**Comment by adrai** [comment]
Why not defining the dependecies as normal in the package.json ?

**Comment by Honigbaum** [comment]
I think the dependencies have to be handled more carefully. If there is a new version pug-parser, which just changed on the patch level, my expectation is that it doesn't break our code. If it's a breaking change I would expect something different than patch level and especially a change in the pug version to 2.0.1.

**Comment by ForbesLindesay** [comment]
pug-parser 4.0.1 was released by accident, and should have been 5.0.0.  4.0.2 was manually released from the 4.0.0 tag on git. Please stop using git tags as the source of truth and start using npm versions.  Failing that, simply update to pug@2.0.1 which uses pug-parser 5.0.0
