### ISSUE TITLE
Mixin attributes argument are not working as expected

### ISSUE THREAD

**Issue by FilippoIOVINE** [pugjs/pug#3016]
**Pug Version:** 2.0.3

## Input Pug

```pug
mixin test
    if attributes.a
        p=attributes.a
    if attributes.b
        p=attributes.b
    p&attributes(attributes)/

div
    div
        p test 1
        +test(a=true, b)

    div
        p test 2
        +test(a, b)
```
## Expected HTML

```html
<div>
    <div>
        <p>test 1</p>
        <p>true</p>
        <p>true</p>
        <p a="a" b="b"/>
    </div>
    <div>
        <p>test 2</p>
        <p>true</p>
        <p>true</p>
        <p a="a" b="b"/>
    </div>
</div>
```

## Actual HTML

```html
<div>
    <div>
        <p>test 1</p>
        <p>true</p>
        <p>true</p>
        <p a="a" b="b"/>
    </div>
    <div>
        <p>test 2</p>
        <p/>
    </div>
</div>
```

## Additional Comments

Hi,
I am expecting to have attributes argument in a mixin begin set to true even if I do not set any value, instead I got undefined:
+test(a, b) -> a=undefined, b=undefined

So I need to set at least the first argument to any value to let all attributes being work correctly:
+test(a=true, b) -> a=true, b=true

Thanks for your support, awesome product. :)

Cheers,
Filippo

**Comment by ForbesLindesay** [comment]
The problem here is that:

```pug
mixin test
```

is actually short for:

```pug
mixin test()
```

i.e. a mixin taking 0 parameters

and

```pug
+test(a=true, b)
```

is short for:

```pug
+test()(a=true, b)
```

i.e. call a mixin with 0 arguments and some attributes

```pug
+test(a, b)
```

therefore means "call test with the arguments `a` and `b`".

You would have to write:

```pug
+test()(a, b)
```

There's really not much we can do to improve this I'm afraid.

We do attempt to explain this in the second "Note" on https://pugjs.org/language/mixins.html#mixin-attributes but perhaps it could be explained more clearly. If you want to improve it, please submit a pull request to https://github.com/pugjs/pug-en/blob/master/src/language/mixins.md
