### ISSUE TITLE
 Jade and Node.js : no action when click on submit on post method WHAT TO DO NOW

### ISSUE THREAD

**Issue by Obaid-ur-Rehman-CIIT-Islamabad** [pugjs/pug#3102]
##APP.JS FILE
![01](https://user-images.githubusercontent.com/27363232/52131269-2cafa280-265e-11e9-83d6-dcdfeacf0dda.PNG)

##JADE FILE
![02](https://user-images.githubusercontent.com/27363232/52131277-320ced00-265e-11e9-892b-44488f25bf38.PNG)

##HTML PREVIEW
![03](https://user-images.githubusercontent.com/27363232/52131360-67193f80-265e-11e9-95d4-599459b4dd75.PNG)

When I click on Submit button nothing happens control stays on same page.
I am realy stuck at this point, any help will be apprecaited.

Thank you

**Comment by jeromew** [comment]
Sorry but this is far from a pug question. This issue tracker is dedicated to problem with pugs. You should ask your question on stack overflow for instance.

From a far away glance at your code, you should make sure that the elements inside your form are indented so that they are indeed inside the form. Hope that helps.
