### ISSUE TITLE
wbr tag renders extra space

### ISSUE THREAD

**Issue by Martinomagnifico** [pugjs/pug#3126]
**Pug Version: 2.0.3

**Node Version: 10.15.1

## Input Pug

```pug
label Lorem ipsum dolor sit consectetur/#[wbr]adipiscing?
```

## Expected HTML

```html
<label>Lorem ipsum dolor sit consectetur/<wbr>adipiscing?</label>
```

## Actual HTML

```html
<label>Lorem ipsum dolor sit consectetur/
                              <wbr>adipiscing?
                            </label>
```

## Additional Comments

The browsers (Safari/Chrome) show it as: "**Lorem ipsum dolor sit consectetur/ adipiscing?**" with an extra space, which is exactly what we don't want. (The reason for the `<wbr>` was to allow a word-break, but not force it, and to keep the words and the slash together.)

**Comment by ForbesLindesay** [comment]
You're using `pretty` mode for pug. Please disable `pretty` mode.

**Comment by Martinomagnifico** [comment]
Then the prettifier does not understand the wbr tag correctly. It is supposed to be used in the middle of words and stay there, even if the HTML is run through a prettifier.  If I write pretty HTML and break a word, that empty space will show, regardless if there’s a wbr tag or not. See a simple example like this one: https://www.geeksforgeeks.org/html-5-wbr-tag/amp/ That is pretty HTML, except... the wbr tag. Thanks for the suggestion, but “please disable pretty mode” is not a solution. I’m trying to help the development of Pug here, hence the original issue.

**Comment by ForbesLindesay** [comment]
Pug output is not intended to be read by humans. `pretty` mode is there for debugging and generating documentation. It should not be considered reliable/useable in real world applications because the rules about where whitespace does and does not make a difference in HTML depend on the CSS rules in play, so they cannot be determined up front. For this reason, I suggest you disable pretty mode, and if you need pretty output you can use a third party html prettifier.
