### ISSUE TITLE
Can't access pug mixin argument inside block

### ISSUE THREAD

**Issue by henriquehbr** [pugjs/pug#3160]
**Pug Version:** 2.0.4

**Node Version:** 11.15.0

```js
app.set("view engine", "pug");
app.set("views", __dirname + "/../frontend/views");
pug.renderFile('input');
```

**mdc-dialog.pug**
```pug
extends mdc-auto-init
mixin mdc-dialog(parameters)
    //- Mixin code here...
    block append mdc-auto-init
        script.
            var #{parameters.id} = "foobar";
```

**mdc-auto-init**
```pug
mixin mdc-auto-init()
    block mdc-auto-init
        //- "helloWorld" is the variable name. coming from (parameters.id)
        h1= helloWorld
```

The following error is being returned

     
```
     24|     block append mdc-auto-init
     25|         script.
   > 26|             var #{parameters.id} = "foobar";

Cannot read property 'id' of undefined
```

**Comment by ForbesLindesay** [comment]
block append doesn't work inside mixins. This is by design, they're just not intended to work that way.

The other problem is that the `script` tag is javascript to run client side, not during template rendering. You need to use `- var something = "foobar";` if you want code to run during template rendering, but you cant use interpolation with that.
