### ISSUE TITLE
Invalidating pug template cache by a render option or api

### ISSUE THREAD

**Issue by bbalban** [pugjs/pug#3176]
**Pug Version:** 2.0.3
**Node Version:** 10.16.0

Hello. I am editing and dynamically reloading pug files at run-time. I had to invalidate the pug cache with the following "hack" below. I was wondering if this could be an acceptable option if I produced a patch for it, or even better a separate API was available to do this in advance before rendering.

Thanks!
Bahadir

```
function handleTemplateCache (options, str) {
  var key = options.filename;
  if (options.cache == "invalidate") {
    console.log("Invalidating cache key: ", key)
    delete exports.cache[key];
  }
...
```

How I used it:
```
res.render('landing', { cache: "invalidate", landing, features, user: req.user });
```

**Comment by ForbesLindesay** [comment]
It's not a good idea for security to allow pug templates to change at runtime - a user who can supply a pug template would be able to run arbitrary code on your server and gain direct access to databases, private keys etc. Less important, but still worth considering, compiling a pug template is slow, and involves synchronous IO. Your server will be un-responsive for the entire time that's happening, which could lead to significant down time for your app.

 Because of this, i don't want to add an option to make this any easier.

That being said, you can handle the caching outside of pug fairly easily by using the lower level `pug.compile`/`pug.compileFile` APIs, which return functions. You can then just cache those functions any way you choose.
