### ISSUE TITLE
Sending data to pug then to a js file securely

### ISSUE THREAD

**Issue by cakerake** [pugjs/pug#3178]
I'm using the latest pug version with express

There is session data available in the req which is also available as a local and accessible via the 'session' parameter in pug

at first i was handling all session related stuff inside pug and then decided to have a js file dedicated to all session work in an effort to make it a bit more secure.

im trying to pass the data that is passed from express to pug -> to a javascript file defined in pug as so : 

`script.
  var session = !{JSON.stringify(session)}
   script(src='/js/tracking.bundle.js')`

This works but it also prints out the session in the html....

how do i make it more secure? i want to pass the data to tracking.bundle.js in the safest possible manner from pug

**Comment by ForbesLindesay** [comment]
If its running client side, it can be inspected and read by the user. Whether it's in the HTML or embedded directly in the script or part of a cookie doesn't make any difference. The only thing I would recommend is that you use https://www.npmjs.com/package/js-stringify instead of `JSON.stringify` as using `JSON.stringify` inside `!{...}` could be vulnerable to XSS.
