### ISSUE TITLE
Deprecated Dependencies - core-js

### ISSUE THREAD

**Issue by NicoBougrand** [pugjs/pug#3205]
Issue when installing pug.
 npm i pug @types/pug
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3

The core-js 2.... is deprecated, should use core-js > 3.

Regards,
Nicolas

**Comment by YasharF** [comment]
I investigated this issue:
The cause of core-js being flagged is because pug-filters, pug-attrs, and pug-code-gen are using an older version of constantinople.  The latest version of constantinople which @ForbesLindesay has already released has moved to babel 7 and no longer has the issue, but it looks like the above three oug subpackages need to pick up this more recent version of constantinople.

"constantinople": "^3.1.2" >> "babel-types": "^6.26.0" >> "babel-runtime": "^6.26.0" >> "core-js": "^2.4.0"

**Comment by YasharF** [comment]
(correction to my prior posting): https://github.com/pugjs/pug/commit/201b9c78431e172dc90a6d258af982e2d1191da8 was supposed to fix the issue since the out of date version of core-js was getting pulled in because of an older version of constantinople ("constantinople": "^3.1.2" >> "babel-types": "^6.26.0" >> "babel-runtime": "^6.26.0" >> "core-js": "^2.4.0").  It looks like that even though the fix made it to git-hub, it hasn't been pushed to npm.

**Comment by cekvenich** [comment]
Ideally, this is just updating package json and doing a release.
