### ISSUE TITLE
Considering updating the dependencies to fix vulnerability issue?

### ISSUE THREAD

**Issue by jdneo** [pugjs/pug#3225]
**Pug Version:** 2.0.4

<img width="262" alt="Screen Shot 2020-03-29 at 12 14 46 PM" src="https://user-images.githubusercontent.com/6193897/77840187-0da39680-71b7-11ea-9216-48627dd3a44b.png">

Reference: https://app.snyk.io/vuln/SNYK-JS-ACORN-559469

**Comment by andreubotella** [comment]
Also:
![Screenshot from 2020-03-31 19-38-51](https://user-images.githubusercontent.com/8225977/78057601-485c2900-7387-11ea-9f35-244963b4eb60.png)

In this case, updating `uglify-js` to 3.0.0 or higher would do.

Reference: https://github.com/advisories/GHSA-6c8f-qphg-qjgp

**Comment by DrEsteban** [comment]
Any plans for an update for acorn dependency?

**Comment by codingthat** [comment]
The out-of-date dependency on acorn also causes an automated (and not automatically fixable) GitHub security alert, even on a fresh project generated with `npx express-generator --view=pug`: https://github.com/expressjs/generator/issues/258

**Comment by codingthat** [comment]
``` sh
$ yarn why acorn
yarn why v1.22.4
[1/4] Why do we have the module "acorn"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "acorn@4.0.13"
info Has been hoisted to "acorn"
info Reasons this module exists
   - Hoisted from "pug#pug-lexer#is-expression#acorn"
   - Hoisted from "pug#pug-code-gen#with#acorn-globals#acorn"
info Disk size without dependencies: "672KB"
info Disk size with unique dependencies: "672KB"
info Disk size with transitive dependencies: "672KB"
info Number of shared dependencies: 0
=> Found "with#acorn@3.3.0"
info This module exists because "pug#pug-code-gen#with" depends on it.
info Disk size without dependencies: "676KB"
info Disk size with unique dependencies: "676KB"
info Disk size with transitive dependencies: "676KB"
info Number of shared dependencies: 0
Done in 0.18s.
```

**Comment by ricksterhd123** [comment]
Same issue #3223

**Comment by ricksterhd123** [comment]
Someone did a pull request but a test failed I think something wrong happened in uglifyjs

**Comment by ForbesLindesay** [comment]
There is no actual vulnerability in pug. All of these are false-positives, unless you are rendering un-trusted pug templates, which we do not ever claim to be a safe thing to do.

**Comment by codingthat** [comment]
@ForbesLindesay Maybe so, but I believe that it's a mistake to ignore the developer experience perspective in this case.  Particularly for such a high-profile project as Express.js, this gives new users the impression that pug is broken, even if it isn't—and how should they know otherwise, based on the CLI output?

**Comment by Krinkle** [comment]
@codingthat complain to the authors of npm-cli and npm-audit :)

**Comment by codingthat** [comment]
@Krinkle Should I?  Maybe I'm misunderstanding the situation, but I'm not sure how npm-audit would theoretically know that a project's outdated dependency is OK because where its vulnerability is actually relevant is a case that "we do not ever claim to be a safe thing to do."

I'm also not sure why there's an apparent aversion to keeping dependencies up-to-date to improve UX, even if it's not technically this project's "fault" per se.  ¯\_(ツ)_/¯

I hope everyone reading this can trust that I am suggesting this for the sake of the pug project, from the perspective of someone starting a new project at the time.  I am not here for the sake of complaining.  I am also not here because it personally affects me any further, now that I know I can simply ignore the warning.

If you prefer leaving old dependencies even if it means that new users might be put off by the resulting warning messages, I won't be arguing any further, but I will stay subscribed to this thread in case you would like to correct any misunderstanding I may have.  Thanks!  🙏

**Comment by Krinkle** [comment]
My point is that npm-audit has been useless in most cases to most people because a significant portion of npm's use is powering of local development tooling involving almost by design packages that are inherently not audited for security before use. This isn't like Debian or Ubuntu issuing a CVE against a package of which the authors are known and trusted. Anyone can submit anything to npm. There is no trust to begin with.

There are, in my view, only one cases where an audit warning would be relevant: The code with the vulnerability will be executed on user devices or on production web servers where they are exposed to user input. For any other cirumstance, it's generally just a waste of time.

There is one other case that might be relevant - if the code you use turns out to be from an explicitly malicious package [doing evil things direclty on your machine](https://timotijhof.net/posts/2019/protect-yourself-from-npm/#further-reading). But in that case npm will immediately remove it from the registry instead of just warning you about it. And more importantly, if one cares even a little bit about your personal or company's data, you should never run npm tooling on your laptop anyway, unless done in an isolated VM with limited access to a specific working directory only. Hence, even evil packages don't matter.

Humanity has wasted a ton of time pointlessly updating such packages and/or arguing about why not to, all the while providing a false sense of actual security. Making you think that packages without these warnings are somehow known to be good.

**Comment by codingthat** [comment]
@Krinkle Thank you for taking the time to explain all this (here and in the article you cited.)  That's very helpful to know!  (And still very unfortunate, in terms of UX/DX, not only for npm-audit, but [for GitHub too](https://github.com/expressjs/generator/issues/258). 
 I suppose, so it should be, given the underlying issues you highlighted.)
