### ISSUE TITLE
Does not generate form tag

### ISSUE THREAD

**Issue by tapz** [pugjs/pug#3237]
Why is it tag pug does not generate all tag to html, which are present in pug template? Can I somehow force it to do so. I really hate this kind of "intelligent" logic that tries to be more clever than the one who wrote the template.

The form is inside another form, but that's not something pug should be worried about.

**Pug Version:** 2.0.4

**Node Version:** 12.16.2

## Input Pug

```pug
form(action='/abc/user/doSomething' method='post' id='myForm')
  div.col-xs-4.checkbox-column
    input(style='display: none', name='id', value=customer.userId)
```

## Expected HTML

```html
<form id="myForm" action="/abc/user/doSomething" method="POST">
  <div...>
    <input...
```

## Actual HTML

```html
<div..>
  <input ...
```

**Comment by tapz** [comment]
Added one more form above this form and now both are generated:

```
form(action='fucking buggy pug')
form(action='/abc/user/doSomething' method='post' id='myForm')
```

**Comment by trasherdk** [comment]
@tapz  According to [this](https://stackoverflow.com/questions/379610/can-you-nest-html-forms/54901309#54901309) it seems it's your code that's `fucking buggy`

**Comment by tapz** [comment]
@trasherdk I don't care if HTML5 specs don't allow this. It still works when writing HTML directly. But not in Pug. I don't think Pug should be the one to guard the specs. It should do what I ask it to do.

**Comment by tapz** [comment]
Also, Pug is not consistent. Sometimes it generates nested forms and sometimes not. Should decide if it enforces the specs or not.

What I'm doing is to maintain some old product, which will be completetly rewritten with React at some point. But now I just want to do a quick fix and not waste my time rewriting something, that will be implemented with a far better and more modern technique later.

**Comment by ForbesLindesay** [comment]
pug is not enforcing this. Pug is faithfully generating the HTML you ask for, you're just then looking at the browser's element inspector, which isn't showing you the raw HTML, it's showing you the resulting element structure after applying **the browser** applies rules for the spec. For what it's worth, the output of:

```pug
form(action='/abc/user/doSomething' method='post' id='myForm')
  div.col-xs-4.checkbox-column
    input(style='display: none', name='id', value=42)
```

is actually

```html
<form action="/abc/user/doSomething" method="post" id="myForm">
  <div class="col-xs-4 checkbox-column">
    <input style="display: none" name="id" value="42" />
  </div>
</form>
```

which is valid HTML, so it's something else that's going wrong for you.

If you want to get further help, you will need to post an actual pug template input and html output that match, rather than just snippets like this that don't demonstrate the behaviour you're seeing.

If you post again with obscenities, you will just be blocked. This is your only warning.

**Comment by tapz** [comment]
Thanks @ForbesLindesay, this was helpful.
