### ISSUE TITLE
Feature: specify element class attribute as hash

### ISSUE THREAD

**Issue by bogdan** [pugjs/pug#330]
In my use case I have two dynamic classes on my element. Both controlled by Bollean js value.

In order to handle it I do:

``` jade
.button(class="#{Profile.rulers() && 'rulers'} #{Profile.checker() && 'checker'}")
```

I think it's a good idea to support hash as class argument, like this:

``` jade
.button(class={"rulers": Profile.rulers(), "checker": Profile.checker()})
```

It supposes to be more clean.

What do think?

**Comment by vinhphamthanh** [comment]
I cannot specify a local reference in pug. e.g 
input(type="text", name="content", #local_reference) in which the #local_reference is recognized by Angular 2.

**Comment by jeffwilcox** [comment]
@vinhphamthanh can't you just enclose the attribute in quotes?

```
input(type='text', name='content', '#local_reference')
```

Works for me with the latest Pug RC package at least.

**Comment by vinhphamthanh** [comment]
@jeffwilcox , I tried it but error reported as: (pug -v 2.0.0-beta.12, pug-html-loader -v 1.1.4)

"zone.js?fad3:567 Unhandled Promise rejection: Template parse errors:
There is no directive with "exportAs" set to "#localreference" ("iv class="form-group"><label for="content">Content </label><input class="form-control" id="content" [ERROR ->]#localreference="#localreference" type="text" name="message"/></div><button class="btn btn-primary" t"): ng:///AppModule/MessageInputComponent.html@0:140 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
There is no directive with "exportAs" set to "#localreference" ("iv class="form-group"><label for="content">Content </label><input class="form-control" id="content" [ERROR ->]#localreference="#localreference" type="text" name="message"/></div><button class="btn btn-primary" t"): ng:///AppModule/MessageInputComponent.html@0:140"

**Comment by vinhphamthanh** [comment]
@jeffwilcox, I found the issue just confused me so much, because the resulting HTML rendered did not reflect the attribute in the HTML. But when we I used it, it worked.
For example, 
Pug code: input.form-control#username(type="text", name="username", **#local_reference=""**)
HTML rendering: <input type="text" name="username" id="username" class="form-control">
--> in the HTML, the #local_reference is absent!!!!!! But its function still exists!

But when I use this local reference, it reflect what I expect!!!
Pug code: button.btn.btn-primary(type="submit" (click)="onTest(**local_reference**.value)") Test
HTML rendering: <button class="btn btn-primary">Test</button>

Do you have any idea?

Thanks for your time.
