### ISSUE TITLE
block append/prepend within an include

### ISSUE THREAD

**Issue by jgallen23** [pugjs/pug#426]
I like to keep my css/js dependancies within their includes so that if I remove the module from the page, the ui assets go away with it.  The new block append/prepend is great, but it doesn't seem to work within an include file

**Comment by raduluchian** [comment]
Having the very same issue as @jgallen23 . I'm keeping my CSS/JS dependencies confined to a certain module so that if I remove the module the dependent files get removed as well. 

This wasn't such a big deal for CSS/JS but I'm also loading other Pug files into certain areas (e.g. loading different module-specific blocks into the <aside> tag). This bug means that anything I am appending from the included module doesn't actually get appended to the <aside> but just gets appended to wherever this modules was included.

Since this isn't solve, I would say this bug should be reopened.

**Comment by scootz** [comment]
This is still an issue as I've just come across this same thing with what I was working on.
