### ISSUE TITLE
Feature Request: Dynamic inheritance

### ISSUE THREAD

**Issue by lorenyu** [pugjs/pug#520]
Being able to support dynamic inheritance like Twig does (http://twig.sensiolabs.org/doc/tags/extends.html#dynamic-inheritance) would be awesome.

Something like `extends= layoutName`

This way, if you don't have the "=" sign it will still be interpreted literally so if you want to extend 'layout.jade', you would still just do `extends layout`

**Comment by spbond** [comment]
It seems to me that providing the dynamic behavior that everyone wants with compile extends is a rather simple matter.  Simply compile a different template for each branch, and select the appropriate version at compile time.  JADE doesn't lose any runtime performance, and coders get to keep their code DRY.  This will result in multiple templates, but that would happen anyway if everyone had to manually create multiple versions of their JADE templates.  This also keeps the code cleaner because it doesn't necessitate any clumsy workarounds.
