### ISSUE TITLE
Spaces between buttons

### ISSUE THREAD

**Issue by samholmes** [pugjs/pug#905]
Is there a better way to have spaces between HTML inputs then this:

```
input(type='button)
| 
input(type='button')
```

Otherwise, I could just add some margin around the buttons in CSS, but then when there is space, then there is too much space...

**Comment by rajkumarpb** [comment]
I am trying to use something like below. 

.user
  h2= user.name
  | &nbsp; mail id is
  .email= user.email

But I am getting error saying undefined symbol.  I want my result to be displayed like {name} mail id is {mail}. Let me know how can I do this. Tried a lot from SFO and GH. No use

**Comment by TimothyGu** [comment]
@rajkumarpb 

Do you need the classes?

**Comment by rajkumarpb** [comment]
Yes. It's just to differentiate the email and name.

**Comment by ForbesLindesay** [comment]
I'm locking this issue now as it's got way too much of people just repeating solutions that have already been described and the issue is closed.  @rajkumarpb please open a new issue with the full error message and a minimal example to reproduce the error and someone will look at helping you with it.  Your problem is not the same as this issue is attempting to discuss.

To summarise the options:


**Option 1**

Note the trailing white-space.  Some editors will unfortunately automatically strip this.

```jade
input(type='button')
|  
input(type='button')
```

**Option 2**

Use `style` or `class` to create the extra spacing, without actually adding any white space.

```jade
input(type='button' style='margin-left: 1px;')
input(type='button')
```

**Option 3**

Use jade's support for JavaScript expressions to explicitly buffer the space.

```jade
input(type='button')
= ' '
input(type='button')
```

**Option 4**

Use the `&nbsp;` escape sequence to force the white space:

```jade
input(type='button')
| &nbsp;
input(type='button')
```
