### ISSUE TITLE
Empty new lines in plain text templates

### ISSUE THREAD

**Issue by binarykitchen** [pugjs/pug#912]
Hello there

I want to render a plain text template in jade but have issues with white spaces inside empty new lines.

This is the template I have:

```
| blabbbah
| 
| lallalala
```

My IDE strips trailing white spaces, so I cannot have `|` - it changes that to `|`. As a result I get this after rendering:

```
blabbbah
|
lallalala
```

but I want this:

```
blabbbah

lallalala
```

I cannot disable that IDE feature to strip trailing white space. Is there a workaround for this in Jade?

**Comment by bramey** [comment]
Thanks @rlidwka

**Comment by metamatt** [comment]
Thanks @rlidwka. Even better: `| #{''}`.

**Comment by deedw** [comment]
In case it's still of interest, I use this shorter option:

```
| foo
=' '
| bar
```

or

```
| foo
=''
| bar
```

**Comment by devmckeon** [comment]
Or what I do:
```
-
  var plain = `
  Thank your for your interest!
   
  Follow the link below to see product updates:
  ${link}
   
  Sincerely,
  	Me Us Them 
        bro@them.local
   
  	
  -------------------------------------------------
  To unsubscribe visit: https://them.local/unsubscribe/
  `;
!= plain
```
Downside is that you have to indent everything to the code block level (but the template string come's out looking fine), env must support template strings, and you appear to have to indent blank lines with whitespace so that you have a single space present past the indentation level; but I prefer the clean look. =)

On this note, it would be great is code blocks did NOT remove blank lines (preventing the need to indent blank lines in this case, but also outputting more readable code and prevent afffecting template strings in code now that they are commonplace). =P
