### ISSUE TITLE
Include Directory

### ISSUE THREAD

**Issue by jescalan** [pugjs/pug#916]
So I was thinking it would be nice if the include function would include all the files in a folder if the name of a folder was passed. I'm not sure off the top how the include functionality works, but if I had to guess based on what I know, it  just concats the file path with the string after include, adds '.jade' to the end, and if that file exists renders its contents in place of the include. If this is how it works, it should be easy to add one more test to see if the file is a directory in between and if so render out each of the contained files.

Would be happy to give this a shot via pull requests if it seems like something people want and if you are ok with it, TJ/maintainers.

**Comment by KellyLSB** [comment]
@kentcdodds @TechplexEngineer

To answer @ForbesLindesay, the files are loaded in lexically.
For an example you can look at https://github.com/KellyLSB/kellybecker.me/blob/f29d5415ed4a282219e25909aef910b569648b8c/_src/jade/resume.jade#L5 and https://github.com/KellyLSB/kellybecker.me/tree/f29d5415ed4a282219e25909aef910b569648b8c/_src/jade/includes/mixins

So then you would prefix each template with a number otherwise it loads sequentially according to the  respective [ascii decimal code](http://www.asciitable.com) (I would assume). 

Note https://github.com/KellyLSB/jade-glob-include only works in Node.JS (pull requests welcome).

**Comment by TimothyGu** [comment]
@KellyLSB said:
> To answer @ForbesLindesay, the files are loaded in lexically.

I have never doubted that the answer is "lexically," but the more important question is how we should offer users a way to *change* the order (e.g. descending/ascending). If we add an option with the existing options API, it will overarch all the glob includes in the file, which is undesirable.

> Note https://github.com/KellyLSB/jade-glob-include only works in Node.JS (pull requests welcome).

I would not expect it to work in the browser anyway.

**Comment by arxpoetica** [comment]
+1

**Comment by fusepilot** [comment]
+1. Same use case as @kentcdodds.
