### ISSUE TITLE
livescript filter

### ISSUE THREAD

**Issue by legomind** [pugjs/pug#939]
any change of getting a livescript filter added?

**Comment by tarwich** [comment]
I'm confused. This is done as of [Jun 30, 2014](https://github.com/ForbesLindesay/transformers/commit/f4809b27a710c1eb9ebcb2a1cf92d7b092ee9f42), but I don't seem to be able to use it in Jade.

**Comment by TimothyGu** [comment]
@tarwich Works fine here. Note that you need to use proper capitalization "LiveScript"

```
$ cd jade
$ npm install
$ npm install LiveScript
```

```jade
//- live.jade
script
  :LiveScript
    table1 =
      * id: 1
        name: 'george'
      * id: 2
        name: 'mike'
      * id: 3
        name: 'donald'
```

```sh
$ cat live.jade | bin/jade.js
```

```html
<script>// Generated by LiveScript 1.3.1
(function(){
  var table1;
  table1 = [
    {
      id: 1,
      name: 'george'
    }, {
      id: 2,
      name: 'mike'
    }, {
      id: 3,
      name: 'donald'
    }
  ];
}).call(this);
</script>
```

**Comment by tarwich** [comment]
Cool. That's how I would expect it to work. But... It's not :disappointed:. Perhaps I'm using the wrong version of something?

````
> npm install -g jade
> npm install -g LiveScript
> jade test.jade

/usr/local/lib/node_modules/jade/lib/runtime.js:231
  throw err;
        ^
Error: test.jade:4
    2|  body
    3|          script
  > 4|                  :LiveScript
    5|                          setTimeout(_, 1000) ->
    6|                                  console.log 'Works'

unknown filter ":LiveScript"
    at filter (/usr/local/lib/node_modules/jade/lib/filters.js:12:11)
    at Object.Compiler.visitFilter (/usr/local/lib/node_modules/jade/lib/compiler.js:507:19)
    at Object.Compiler.visitNode (/usr/local/lib/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/usr/local/lib/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitBlock (/usr/local/lib/node_modules/jade/lib/compiler.js:295:12)
    at Object.Compiler.visitNode (/usr/local/lib/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/usr/local/lib/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitTag (/usr/local/lib/node_modules/jade/lib/compiler.js:478:12)
    at Object.Compiler.visitNode (/usr/local/lib/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/usr/local/lib/node_modules/jade/lib/compiler.js:212:10)
````

Other failed invocations:
````
> npm install -g jade LiveScript
> jade test.jade

> npm install -g jade LiveScript
> npm install jade LiveScript
> jade test.jade
````

Oh, and 
````
> jade --version
1.9.1
````

**Comment by TimothyGu** [comment]
Oh, it's not really your fault. Jade 1.9.1 still uses an older version of transformers. It is only recently updated by me in 8fd2b6c5e32f45204a777cb801ae6f0ac2544565. I don't have the privilege to publish new releases (yet), but I assume @ForbesLindesay will soon make a new release.

**Comment by tarwich** [comment]
Cool! Since I'm using Express, I'll just do this for now: 
https://github.com/ForbesLindesay/transformers/issues/36

Thanks for the help!

**Comment by ForbesLindesay** [comment]
@TimothyGu you need to start using pull reuqests.  That change **can't** go in until 2.0.0 is released because that updates transformers to a version that contains breaking changes (it removes some old and less used transformers that some people could be depending on).  In addition, it depends on a GitHub url, rather than an npm version number, which makes it very brittle, and would break installation of jade in environments that don't have `git`.  If we have to use a version of a library that has yet to be published to npm, we can do so, but at least we should use the tarball url instead for this reason.  In practice I can just release a new version of transformers.

The biggest problem in all of this is that the mistake happened 16 days ago, but I didn't find out about it until now.  Pull requests prevent exactly this kind of problem.  This repo has two golden rules:

1. Don't commit directly to master (except README.md, and the things that are updated as part of a release).
2. Only merge your own pull request if it has been ignored for a prolonged period of time.  If you update it because of feedback, allow time for that feedback to be reviewed.

@tarwich sorry about all of this.  We will have a much better answer for you once jade@2.0.0 is released, which I do intend to be soon (No later than 9th March).  In the mean time, adding the custom filter as you suggested is by far the easiest way of making this work.

**Comment by TimothyGu** [comment]
@tarwich I'm really sorry about this too.

@ForbesLindesay sorry about that. I thought I did but seems like I didn't. Will take care of this next time. Same goes for all other commits. Feel free to revert them.

**Comment by ForbesLindesay** [comment]
As far as I can tell, the end results of the other commits are all good, so there's no point reverting them now :)
